-- ==========================================================
-- Learning Hub - Answer-key reconciliation
--
-- Rewrites the `data` payload of every activity block to match the
-- official "Final References and Key to Correction" document:
--   * corrected answer keys where the seeded answer disagreed with it;
--   * the target word actually marked __underlined__ in the prompts that
--     refer to "the underlined word";
--   * `"subjective": true` on every question the key records as
--     "Answers may vary", with the key's model answer kept in
--     `sampleAnswer` for the teacher's review screen.
--
-- This UPDATEs blocks in place, matched on module title + block title, so
-- student progress, highlights and assignments all survive — unlike
-- re-running the seed files, which drop and re-insert the modules.
--
-- Safe to re-run. Run AFTER the seed_content_*.sql files and
-- add_subjective_review.sql.
-- ==========================================================

update module_content mc
set data = '{"instructions": "Directions: For each everyday vocabulary word below, select its correct meaning from the dropdown.", "questions": [{"id": "q1", "type": "matching", "prompt": "Match each term to its meaning.", "points": 5, "pairs": [{"left": "Jeepney", "right": "Public transport commonly used in the Philippines"}, {"left": "Registrar''s Office", "right": "University office that manages student records"}, {"left": "Tuition", "right": "Payment for education"}, {"left": "Sari-sari Store", "right": "Small neighborhood store"}, {"left": "Barangay Clearance", "right": "Required document from your local government unit"}]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 1: Everyday Vocabulary – Match the Term';

update module_content mc
set data = '{"instructions": "Directions: Interactive text: \"During my first week at the university, I reviewed the syllabus for each subject, attended my first lecture, and visited the campus library. I also asked about internship opportunities and checked the deadline for dropping courses.\"\n\nFor each academic term below, select its correct definition from the dropdown.", "questions": [{"id": "q1", "type": "matching", "prompt": "Match each academic term to its definition.", "points": 5, "pairs": [{"left": "Syllabus", "right": "A summary outline of topics and activities in a course"}, {"left": "Lecture", "right": "A formal educational talk given by a professor"}, {"left": "Deadline", "right": "The latest time by which something should be submitted"}, {"left": "Internship", "right": "Practical work experience in a field of study"}, {"left": "Campus", "right": "The grounds and buildings of a university"}]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 2: Academic Vocabulary – Match the Term';

update module_content mc
set data = '{"instructions": "Directions: Write an original sentence using each word below. Make sure each sentence reflects a real-life academic or school-related situation. Example — Classroom: \"The classroom was prepared for our group presentation.\"", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __portal__", "points": 1, "sampleAnswer": "The portal lets me view my grades and assignments."}, {"id": "q2", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __modules__", "points": 1, "sampleAnswer": "We were given multiple modules for asynchronous learning."}, {"id": "q3", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __enrollment__", "points": 1, "sampleAnswer": "I completed my enrollment online with minimal help."}, {"id": "q4", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __thesis__", "points": 1, "sampleAnswer": "My thesis proposal was approved after revision."}, {"id": "q5", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __dean''s office__", "points": 1, "sampleAnswer": "I went to the Dean''s Office to ask about overload forms."}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 3: Academic Vocabulary in Action';

update module_content mc
set data = '{"instructions": "Directions: Choose the most suitable synonym to replace the __underlined__ word in each sentence.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "The professor held a __webinar__ on mental health awareness.", "points": 1, "options": ["online lecture", "meeting"], "correctIndex": 0}, {"id": "q2", "type": "multiple_choice", "prompt": "I received __feedback__ on my performance.", "points": 1, "options": ["criticism", "response"], "correctIndex": 1}, {"id": "q3", "type": "multiple_choice", "prompt": "The school''s __repository__ stores all thesis submissions.", "points": 1, "options": ["archive", "drive"], "correctIndex": 0}, {"id": "q4", "type": "multiple_choice", "prompt": "My __assessment__ was based on quizzes and participation.", "points": 1, "options": ["test", "review"], "correctIndex": 0}, {"id": "q5", "type": "multiple_choice", "prompt": "I had a heavy __course load__ this semester.", "points": 1, "options": ["schedule", "number of subjects"], "correctIndex": 1}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 4: Vocabulary Connections – Choosing the Right Synonym';

update module_content mc
set data = '{"instructions": "Directions: Complete the conversation using the most appropriate vocabulary from the box: Advisor, Cafeteria, Lecture, Scholarship, Classroom, Library.\n\nAna: \"Hey, have you submitted your ___ form?\"\nLance: \"Yes, I brought it to the ___ yesterday.\"\nAna: \"Same! I also stopped by the ___ to get lunch before heading to the ___ to return a book.\"\nLance: \"Cool! Let''s talk later after our ___ with the professor.\"", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Blank (1): \"...submitted your ___ form?\"", "points": 1, "acceptedAnswers": ["Scholarship"]}, {"id": "q2", "type": "short_answer", "prompt": "Blank (2): \"I brought it to the ___ yesterday.\"", "points": 1, "acceptedAnswers": ["Advisor", "Advisor''s Office"]}, {"id": "q3", "type": "short_answer", "prompt": "Blank (3): \"...stopped by the ___ to get lunch...\"", "points": 1, "acceptedAnswers": ["Cafeteria"]}, {"id": "q4", "type": "short_answer", "prompt": "Blank (4): \"...heading to the ___ to return a book.\"", "points": 1, "acceptedAnswers": ["Library"]}, {"id": "q5", "type": "short_answer", "prompt": "Blank (5): \"...after our ___ with the professor.\"", "points": 1, "acceptedAnswers": ["Lecture"]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 5: Contextual Dialogue Completion';

update module_content mc
set data = '{"instructions": "Directions: Add the appropriate prefix or suffix to each root word. You may write just the affix (for example, __-ment__) or the complete word (__management__).", "questions": [{"id": "q1", "type": "short_answer", "prompt": "manage → ____", "points": 1, "acceptedAnswers": ["-ment", "ment", "management"]}, {"id": "q2", "type": "short_answer", "prompt": "enroll → ____", "points": 1, "acceptedAnswers": ["re-", "re", "re-enroll", "reenroll"]}, {"id": "q3", "type": "short_answer", "prompt": "prepare → ____", "points": 1, "acceptedAnswers": ["un-", "un", "unprepared"]}, {"id": "q4", "type": "short_answer", "prompt": "educate → ____", "points": 1, "acceptedAnswers": ["-tion", "tion", "education"]}, {"id": "q5", "type": "short_answer", "prompt": "organize → ____", "points": 1, "acceptedAnswers": ["-er", "er", "organizer"]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 1: Word Formation Drill';

update module_content mc
set data = '{"instructions": "Directions: Identify and correct the morphological error in each sentence.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "The team was very disorganizated.", "points": 1, "acceptedAnswers": ["disorganized"]}, {"id": "q2", "type": "short_answer", "prompt": "Please submital the form before the deadline.", "points": 1, "acceptedAnswers": ["submit"]}, {"id": "q3", "type": "short_answer", "prompt": "They are unconfidence in speaking.", "points": 1, "acceptedAnswers": ["unconfident"]}, {"id": "q4", "type": "short_answer", "prompt": "We will preparize the documents by tomorrow.", "points": 1, "acceptedAnswers": ["prepare"]}, {"id": "q5", "type": "short_answer", "prompt": "I was misunderstook by the teacher.", "points": 1, "acceptedAnswers": ["misunderstood"]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 2: Error Identification and Correction';

update module_content mc
set data = '{"instructions": "Directions: Complete the chart with related forms for each root word (noun, verb, and adjective form).", "questions": [{"id": "q1n", "type": "short_answer", "prompt": "Act — Noun form", "points": 1, "acceptedAnswers": ["action"]}, {"id": "q1v", "type": "short_answer", "prompt": "Act — Verb form", "points": 1, "acceptedAnswers": ["act"]}, {"id": "q1a", "type": "short_answer", "prompt": "Act — Adjective form", "points": 1, "acceptedAnswers": ["active"]}, {"id": "q2n", "type": "short_answer", "prompt": "Decide — Noun form", "points": 1, "acceptedAnswers": ["decision"]}, {"id": "q2v", "type": "short_answer", "prompt": "Decide — Verb form", "points": 1, "acceptedAnswers": ["decide"]}, {"id": "q2a", "type": "short_answer", "prompt": "Decide — Adjective form", "points": 1, "acceptedAnswers": ["decisive"]}, {"id": "q3n", "type": "short_answer", "prompt": "Organize — Noun form", "points": 1, "acceptedAnswers": ["organization"]}, {"id": "q3v", "type": "short_answer", "prompt": "Organize — Verb form", "points": 1, "acceptedAnswers": ["organize"]}, {"id": "q3a", "type": "short_answer", "prompt": "Organize — Adjective form", "points": 1, "acceptedAnswers": ["organized"]}, {"id": "q4n", "type": "short_answer", "prompt": "Succeed — Noun form", "points": 1, "acceptedAnswers": ["success"]}, {"id": "q4v", "type": "short_answer", "prompt": "Succeed — Verb form", "points": 1, "acceptedAnswers": ["succeed"]}, {"id": "q4a", "type": "short_answer", "prompt": "Succeed — Adjective form", "points": 1, "acceptedAnswers": ["successful"]}, {"id": "q5n", "type": "short_answer", "prompt": "Apply — Noun form", "points": 1, "acceptedAnswers": ["application"]}, {"id": "q5v", "type": "short_answer", "prompt": "Apply — Verb form", "points": 1, "acceptedAnswers": ["apply"]}, {"id": "q5a", "type": "short_answer", "prompt": "Apply — Adjective form", "points": 1, "acceptedAnswers": ["applicable"]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 3: Word Family Table';

update module_content mc
set data = '{"instructions": "Directions: Rearrange the words to form grammatically correct sentences.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Unscramble: submitted / the / already / group / has / report / our", "points": 1, "acceptedAnswers": ["Our group has already submitted the report."]}, {"id": "q2", "type": "short_answer", "prompt": "Unscramble: class / was / the / by / joined / late / student / a", "points": 1, "acceptedAnswers": ["A student joined the class late.", "The class was joined by a late student."]}, {"id": "q3", "type": "short_answer", "prompt": "Unscramble: assignments / checking / is / now / professor / the / our", "points": 1, "acceptedAnswers": ["Our professor is checking the assignments now.", "Our professor is now checking assignments."]}, {"id": "q4", "type": "short_answer", "prompt": "Unscramble: day / it / tiring / very / a / was", "points": 1, "acceptedAnswers": ["It was a very tiring day."]}, {"id": "q5", "type": "short_answer", "prompt": "Unscramble: quiet / library / in / the / be / should / we", "points": 1, "acceptedAnswers": ["We should be quiet in the library."]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 1: Sentence Unscrambling';

update module_content mc
set data = '{"instructions": "Directions: Combine the two sentences into one using an appropriate connector.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Combine: \"She was tired.\" + \"She finished the work.\"", "points": 1, "acceptedAnswers": ["Although she was tired, she finished the work.", "She was tired, but she finished the work."]}, {"id": "q2", "type": "short_answer", "prompt": "Combine: \"The class started.\" + \"He was still outside.\"", "points": 1, "acceptedAnswers": ["When the class started, he was still outside.", "The class started, but he was still outside."]}, {"id": "q3", "type": "short_answer", "prompt": "Combine: \"I studied hard.\" + \"I passed the exam.\"", "points": 1, "acceptedAnswers": ["Because I studied hard, I passed the exam.", "I studied hard, so I passed the exam."]}, {"id": "q4", "type": "short_answer", "prompt": "Combine: \"It rained.\" + \"We played indoors.\"", "points": 1, "acceptedAnswers": ["Since it rained, we played indoors.", "It rained, so we played indoors."]}, {"id": "q5", "type": "short_answer", "prompt": "Combine: \"The teacher arrived.\" + \"The students became silent.\"", "points": 1, "acceptedAnswers": ["As soon as the teacher arrived, the students became silent.", "When the teacher arrived, the students became silent."]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 2: Sentence Combination Practice';

update module_content mc
set data = '{"instructions": "Directions: Choose the option that best completes or corrects each sentence.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Subject-Verb Agreement: The group of students ___ preparing for the school presentation.", "points": 1, "options": ["are", "were", "is", "have"], "correctIndex": 2}, {"id": "q2", "type": "multiple_choice", "prompt": "Verb Tense: Yesterday, the students ___ their research project to the panel.", "points": 1, "options": ["present", "presented", "presenting", "have presented"], "correctIndex": 1}, {"id": "q3", "type": "multiple_choice", "prompt": "Sentence Structure: Which sentence is grammatically correct?", "points": 1, "options": ["The students finished their assignment they submitted it on time.", "The students finished their assignment, and they submitted it on time.", "The students finishing their assignment, they submitted on time.", "The students their assignment finished and submitted it on time."], "correctIndex": 1}, {"id": "q4", "type": "multiple_choice", "prompt": "Correct Use of Modifiers: Which sentence has the clearest, most appropriate placement of the modifier?", "points": 1, "options": ["The teacher explained carefully the difficult lesson to the students.", "The teacher carefully explained the difficult lesson to the students.", "The teacher explained the difficult carefully lesson to the students.", "Carefully the teacher explained to the students the difficult lesson."], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Sentence Combination: \"The students studied diligently. They wanted to achieve high grades.\" Which sentence best combines the two ideas?", "points": 1, "options": ["The students studied diligently, because achieving high grades.", "The students studied diligently they wanted to achieve high grades.", "The students studied diligently because they wanted to achieve high grades.", "The students because wanted to achieve high grades studied diligently."], "correctIndex": 2}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Activity 3: Practicing Syntactic Competence';

update module_content mc
set data = '{"instructions": "Directions: Read each question carefully and choose the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "What is the correct formal version of this sentence: \"We had so many quizzes, super stress me.\"?", "points": 1, "options": ["We had lots of quizzes, so it was fun.", "We had many quizzes, and I was very stressed.", "There were lots of quizzes, and everyone passed.", "I did well despite the many quizzes."], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "Which word correctly completes this sentence: \"Our group has already ___ the report.\"", "points": 1, "options": ["submit", "submitting", "submitted", "submission"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Which of the following is a correct example of morphological competence?", "points": 1, "options": ["Misusing punctuation in a sentence", "Saying \"He goed to school\"", "Using \"re-enroll\" to mean enroll again", "Forgetting to capitalize a proper noun"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Which sentence uses proper academic syntax?", "points": 1, "options": ["I text u later if I get news.", "I will send you a message if I receive an update.", "Will send you update later.", "Maybe I text later when have info."], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "What is the best definition for the word \"tuition\"?", "points": 1, "options": ["A university building", "A type of assignment", "A payment for education", "A classroom activity"], "correctIndex": 2}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 1: Linguistic Competence'
  and mc.title = 'Self-Check & Reflection';

update module_content mc
set data = '{"instructions": "Directions: Recast each informal sentence into a more context-appropriate expression.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Recast: \u201cWhat time are you coming?\u201d", "points": 1, "acceptedAnswers": ["What time will you arrive?", "What time will you be arriving?"]}, {"id": "q2", "type": "short_answer", "prompt": "Recast: \u201cI\u2019m late. Wait a sec.\u201d", "points": 1, "acceptedAnswers": ["I apologize, I will be there shortly.", "I apologize for being late; please wait a moment."]}, {"id": "q3", "type": "short_answer", "prompt": "Recast: \u201cI don\u2019t know anything about that.\u201d", "points": 1, "acceptedAnswers": ["I''m not familiar with that topic.", "I\u2019m not familiar with that topic.", "I\u2019m not familiar with that, unfortunately."]}, {"id": "q4", "type": "short_answer", "prompt": "Recast: \u201cWhy didn\u2019t he come?\u201d", "points": 1, "acceptedAnswers": ["Do you know why he was absent?", "May I ask why he was unable to attend?"]}, {"id": "q5", "type": "short_answer", "prompt": "Recast: \u201cMan, the test was so hard!\u201d", "points": 1, "acceptedAnswers": ["The test was quite challenging.", "The examination was quite challenging."]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 2: Sociolinguistic Competence'
  and mc.title = 'Activity 1: Expression Recasting';

update module_content mc
set data = '{"instructions": "Directions: Write both a formal and an informal version of each situation below. Answers may vary — your teacher will read and score these.", "questions": [{"id": "q1f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Inviting a classmate to group work", "points": 1, "sampleAnswer": "Would you like to join our group for this activity?"}, {"id": "q1i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Inviting a classmate to group work", "points": 1, "sampleAnswer": "Hey, wanna join our group?"}, {"id": "q2f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Asking a teacher to extend a deadline", "points": 1, "sampleAnswer": "Would it be possible to request a short extension for the deadline?"}, {"id": "q2i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Asking a teacher to extend a deadline", "points": 1, "sampleAnswer": "Can I have a bit more time to pass this?"}, {"id": "q3f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Apologizing for being late", "points": 1, "sampleAnswer": "I apologize for arriving late."}, {"id": "q3i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Apologizing for being late", "points": 1, "sampleAnswer": "Sorry, I''m late!"}, {"id": "q4f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Congratulating a classmate", "points": 1, "sampleAnswer": "Congratulations on your achievement."}, {"id": "q4i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Congratulating a classmate", "points": 1, "sampleAnswer": "Nice job, congrats!"}, {"id": "q5f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Giving feedback on a peer''s work", "points": 1, "sampleAnswer": "Your work was well done overall, though a few areas could be improved."}, {"id": "q5i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Giving feedback on a peer''s work", "points": 1, "sampleAnswer": "Pretty good, but you could tweak a few parts."}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 2: Sociolinguistic Competence'
  and mc.title = 'Activity 2: Writing Formal and Informal Expressions';

update module_content mc
set data = '{"instructions": "Directions: Match the linguistic realization to the appropriate situation.", "questions": [{"id": "q1", "type": "matching", "prompt": "Match each situation to the appropriate expression.", "points": 5, "pairs": [{"left": "Asking a friend casually", "right": "\u201cBro, do you need help?\u201d"}, {"left": "Talking to a dean formally", "right": "\u201cGood evening, Dean. May I request a short appointment?\u201d"}, {"left": "Making an excuse to a teacher", "right": "\u201cMiss, I wasn\u2019t able to submit it earlier due to an emergency.\u201d"}, {"left": "Casual plan with a peer", "right": "\u201cDude, let\u2019s grab snacks!\u201d"}, {"left": "Clarifying something with a teacher", "right": "\u201cSir, may I clarify something about the lecture?\u201d"}]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 2: Sociolinguistic Competence'
  and mc.title = 'Activity 3: Context Matching';

update module_content mc
set data = '{"instructions": "Directions: Read each statement and decide whether it is appropriate or inappropriate for the given situation. If it is inappropriate, rewrite it using a more context-appropriate form, considering formality, politeness, vocabulary, and the relationship between the speakers. Your teacher will read and score your revisions.", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Situation: You are speaking to your professor after class. \"Hey, can you explain this part again?\"", "points": 1, "sampleAnswer": "Inappropriate. Revised: \"Professor, could you please explain this part again?\""}, {"id": "q2", "type": "short_answer", "subjective": true, "prompt": "Situation: You are messaging your close classmate about a group project. \"Good afternoon. I would like to inquire whether you have completed your assigned portion.\"", "points": 1, "sampleAnswer": "Inappropriate (too formal). Revised: \"Hi! Have you finished your part of the group project?\""}, {"id": "q3", "type": "short_answer", "subjective": true, "prompt": "Situation: You are requesting an extension from your teacher. \"Can you give me more time? I wasn''t able to finish it.\"", "points": 1, "sampleAnswer": "Inappropriate. Revised: \"Ma''am/Sir, may I kindly request an extension for the submission? I was unable to complete the task on time.\""}, {"id": "q4", "type": "short_answer", "subjective": true, "prompt": "Situation: You are talking to your close friend about an upcoming examination. \"I would like to inform you that I am concerned about the difficulty of the examination.\"", "points": 1, "sampleAnswer": "Inappropriate (too formal). Revised: \"I''m kind of worried. The exam might be really difficult.\""}, {"id": "q5", "type": "short_answer", "subjective": true, "prompt": "Situation: You are giving feedback to a classmate about a presentation. \"Your presentation was okay, but you need to do better next time.\"", "points": 1, "sampleAnswer": "Inappropriate (too blunt). Revised: \"Your presentation was good overall. You could improve the organization of your ideas and speak a little more clearly next time.\""}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 2: Sociolinguistic Competence'
  and mc.title = 'Activity 4: Contextual Expression Revision';

update module_content mc
set data = '{"instructions": "Directions: Choose the more polite response for each situation.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "A teacher corrects you. Do you say:", "points": 1, "options": ["\u201cOkay, noted.\u201d", "\u201cThank you for the correction, Ma\u2019am.\u201d"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "You bump into someone in the hallway. Do you say:", "points": 1, "options": ["\u201cSorry, excuse me.\u201d", "\u201cWatch it.\u201d"], "correctIndex": 0}, {"id": "q3", "type": "multiple_choice", "prompt": "You\u2019re late to class. Do you say:", "points": 1, "options": ["\u201cSorry po for being late.\u201d", "\u201cI\u2019m here now, let\u2019s begin.\u201d"], "correctIndex": 0}, {"id": "q4", "type": "multiple_choice", "prompt": "You didn\u2019t understand a lecture. Do you say:", "points": 1, "options": ["\u201cWhat are you talking about?\u201d", "\u201cI didn\u2019t quite catch that. May I ask again?\u201d"], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "You\u2019re asking for an extension. Do you say:", "points": 1, "options": ["\u201cCan you move the deadline?\u201d", "\u201cMay I respectfully request for an extension?\u201d"], "correctIndex": 1}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 2: Sociolinguistic Competence'
  and mc.title = 'Activity 5: Using Appropriate Polite Expression';

update module_content mc
set data = '{"instructions": "Directions: Choose one of the situations below and create a short dialogue of 5\u20136 lines. Use language appropriate to the social context and relationship between the speakers, including tone, politeness, formality, and cultural sensitivity.\n\nChoose one situation:\nA. A student and a dean during a consultation\nB. Two classmates collaborating on a project", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Write your dialogue (5\u20136 lines) for your chosen situation.", "points": 5, "sampleAnswer": "Student: Good afternoon, Dean. May I request a short consultation? Dean: Of course, please come in. Student: Thank you. I wanted to ask about my course load for next semester. Dean: Sure, let''s go over your options together. Student: I really appreciate your time and guidance, Dean. Dean: You''re welcome; feel free to reach out anytime."}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 2: Sociolinguistic Competence'
  and mc.title = 'Activity 6: Creating Context-Appropriate Dialogues';

update module_content mc
set data = '{"instructions": "Directions: Read each question carefully and choose the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Which of the following sentences shows appropriate linguistic realization in a formal setting?", "points": 1, "options": ["\u201cHey Prof, I didn\u2019t get the lesson.\u201d", "\u201cMa\u2019am, can you repeat that part again?\u201d", "\u201cExcuse me, Ma\u2019am. May I ask a clarification regarding the topic?\u201d", "\u201cWhat did you say again, Ma\u2019am?\u201d"], "correctIndex": 2}, {"id": "q2", "type": "multiple_choice", "prompt": "Choose the better expression when making an academic apology:", "points": 1, "options": ["\u201cSorry, I just woke up.\u201d", "\u201cI apologize for being late due to personal reasons.\u201d", "\u201cBetter chill, Ma\u2019am.\u201d", "\u201cI got stuck in traffic, hence, I\u2019m late.\u201d"], "correctIndex": 1}, {"id": "q3", "type": "multiple_choice", "prompt": "Which expression would be most appropriate when speaking to a dean?", "points": 1, "options": ["\u201cDean, I need help.\u201d", "\u201cHi Sir, can I ask a question?\u201d", "\u201cGood afternoon, Dean. May I request for a short consultation?\u201d", "\u201cSir, let\u2019s talk.\u201d"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "In informal situations, which of the following is acceptable?", "points": 1, "options": ["\u201cCan I respectfully ask a favor, bro?\u201d", "\u201cHey dude, let\u2019s grab lunch!\u201d", "\u201cI humbly request your presence, bestie.\u201d", "\u201cGood evening, please allow me to join you.\u201d"], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "What is linguistic realization mainly concerned with?", "points": 1, "options": ["Forming complete sentences", "Choosing the correct spelling of words", "Using language appropriate to the context", "Speaking fluently without pauses"], "correctIndex": 2}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 2: Sociolinguistic Competence'
  and mc.title = 'Self-Check & Reflection';

update module_content mc
set data = '{"instructions": "Directions: Read each paragraph and identify the best topic sentence.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Paragraph 1: Studying in college can be challenging for many students, but time management is crucial for academic success. One way to manage your time effectively is by setting aside specific blocks of time for studying each day. It''s also helpful to avoid distractions, such as turning off your phone while studying. Balancing schoolwork with other commitments can help ensure you stay on top of your studies.", "points": 1, "options": ["College students must develop good time management skills.", "Time management helps balance schoolwork and personal life.", "College life is challenging without effective time management.", "Effective time management can lead to academic success."], "correctIndex": 3}, {"id": "q2", "type": "multiple_choice", "prompt": "Paragraph 2: Many students prefer to study at night when fewer people are around, and the campus is quieter. This can provide a peaceful environment where students can concentrate better. Additionally, for night owls, studying at night aligns with their natural productivity rhythms. On the other hand, others prefer morning study sessions when they feel more refreshed.", "points": 1, "options": ["Students tend to study at night to avoid distractions.", "Quiet study environments are preferred by many students.", "Studying at night can be more effective for some students.", "Night study sessions are preferred by some students for better concentration."], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Paragraph 3: Group projects in college are a great way for students to enhance their communication and collaboration skills. Working with peers allows students to share ideas, brainstorm solutions, and develop a deeper understanding of the subject matter. Additionally, group projects help students learn how to delegate tasks and manage deadlines. However, teamwork also requires patience and flexibility to ensure that everyone''s ideas are considered.", "points": 1, "options": ["Group projects enhance communication and teamwork skills.", "Students often struggle with collaboration during group projects.", "Working in groups is essential for academic success.", "Group projects help students improve collaboration and responsibility."], "correctIndex": 0}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 1: Topic Sentence Identification';

update module_content mc
set data = '{"instructions": "Directions: Rearrange the sentences into a coherent paragraph. Choose the option with the correct order.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Item 1 — a. Finally, we presented our work confidently. b. We brainstormed ideas and selected the best one. c. The group project was a success. d. Everyone contributed during the research phase.", "points": 1, "options": ["c, b, d, a", "b, d, c, a", "d, b, a, c", "a, c, b, d"], "correctIndex": 0}, {"id": "q2", "type": "multiple_choice", "prompt": "Item 2 — a. I checked my backpack to make sure I had everything. b. I quickly got dressed and brushed my teeth. c. When the alarm rang, I jumped out of bed. d. Then I left for school.", "points": 1, "options": ["c, b, a, d", "c, b, d, a", "d, b, c, a", "a, c, b, d"], "correctIndex": 0}, {"id": "q3", "type": "multiple_choice", "prompt": "Item 3 — a. We all clapped and cheered as she crossed the finish line. b. Our classmate joined a local marathon last weekend. c. She trained for weeks to build her stamina. d. During the race, she kept a steady pace and didn''t give up.", "points": 1, "options": ["a, b, c, d", "c, b, d, a", "b, c, d, a", "b, d, c, a"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Item 4 — a. He turned off the lights and closed the door. b. After dinner, my dad washed the dishes. c. Then he watered the plants in the garden. d. When everything was done, he got ready for bed.", "points": 1, "options": ["c, b, a, d", "a, b, c, d", "d, c, b, a", "b, c, a, d"], "correctIndex": 3}, {"id": "q5", "type": "multiple_choice", "prompt": "Item 5 — a. Suddenly, it started to rain heavily. b. I grabbed my umbrella and ran to the bus stop. c. I was walking to school on a cloudy morning. d. I arrived just in time, soaking wet but safe.", "points": 1, "options": ["b, a, c, d", "c, a, b, d", "a, c, b, d", "c, b, a, d"], "correctIndex": 1}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 2: Sequencing Exercise';

update module_content mc
set data = '{"instructions": "Directions: For each set, decide whether the sentence supports the given main idea. Mark True if it belongs, False if it does not.", "questions": [{"id": "q1", "type": "true_false", "prompt": "Main Idea: Watching movies — \"I enjoy watching movies.\"", "points": 1, "correctAnswer": true}, {"id": "q2", "type": "true_false", "prompt": "Main Idea: Watching movies — \"My favorite genres are comedy and action.\"", "points": 1, "correctAnswer": true}, {"id": "q3", "type": "true_false", "prompt": "Main Idea: Watching movies — \"Bananas are high in potassium.\"", "points": 1, "correctAnswer": false}, {"id": "q4", "type": "true_false", "prompt": "Main Idea: Using the internet for learning — \"The internet provides access to unlimited information.\"", "points": 1, "correctAnswer": true}, {"id": "q5", "type": "true_false", "prompt": "Main Idea: Using the internet for learning — \"Many students use it for research and school projects.\"", "points": 1, "correctAnswer": true}, {"id": "q6", "type": "true_false", "prompt": "Main Idea: Using the internet for learning — \"Reading books can improve vocabulary.\"", "points": 1, "correctAnswer": false}, {"id": "q7", "type": "true_false", "prompt": "Main Idea: Physical benefits of basketball — \"Basketball helps improve physical fitness.\"", "points": 1, "correctAnswer": true}, {"id": "q8", "type": "true_false", "prompt": "Main Idea: Physical benefits of basketball — \"Playing regularly builds endurance and coordination.\"", "points": 1, "correctAnswer": true}, {"id": "q9", "type": "true_false", "prompt": "Main Idea: Physical benefits of basketball — \"Math is my least favorite subject in school.\"", "points": 1, "correctAnswer": false}, {"id": "q10", "type": "true_false", "prompt": "Main Idea: Family birthday traditions — \"My family always celebrates birthdays with a special dinner.\"", "points": 1, "correctAnswer": true}, {"id": "q11", "type": "true_false", "prompt": "Main Idea: Family birthday traditions — \"We cook our favorite meals and invite close friends.\"", "points": 1, "correctAnswer": true}, {"id": "q12", "type": "true_false", "prompt": "Main Idea: Family birthday traditions — \"Mount Everest is the highest mountain in the world.\"", "points": 1, "correctAnswer": false}, {"id": "q13", "type": "true_false", "prompt": "Main Idea: Learning English — \"Learning English takes time and practice.\"", "points": 1, "correctAnswer": true}, {"id": "q14", "type": "true_false", "prompt": "Main Idea: Learning English — \"Speaking with native speakers helps improve fluency.\"", "points": 1, "correctAnswer": true}, {"id": "q15", "type": "true_false", "prompt": "Main Idea: Learning English — \"The Great Wall of China is a popular tourist attraction.\"", "points": 1, "correctAnswer": false}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 3: Paragraph Unity Check';

update module_content mc
set data = '{"instructions": "Directions: Write a 5-sentence paragraph on the topic: \"My experience in joining a student organization.\" Ensure unity by staying focused on one main idea.", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Write your 5-sentence paragraph here.", "points": 5, "sampleAnswer": "Joining a student organization helped me grow as a person. I learned how to manage my time between academics and extracurricular activities. I also built new friendships with members who shared the same interests. Through the organization''s projects, I developed leadership and communication skills. Overall, being part of the organization made my college experience more meaningful."}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 4: Short Paragraph Writing';

update module_content mc
set data = '{"instructions": "Directions: Choose the most appropriate cohesive device to complete each sentence.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "I studied hard for the test; __________, I got a high score.", "points": 1, "acceptedAnswers": ["therefore", "as a result", "consequently"]}, {"id": "q2", "type": "short_answer", "prompt": "The weather was bad; __________, we postponed the event.", "points": 1, "acceptedAnswers": ["as a result", "therefore", "so"]}, {"id": "q3", "type": "short_answer", "prompt": "I enjoy writing; __________, I''m not fond of reading.", "points": 1, "acceptedAnswers": ["however", "but"]}, {"id": "q4", "type": "short_answer", "prompt": "She is good at singing. __________, she can also play the guitar.", "points": 1, "acceptedAnswers": ["in addition", "moreover", "furthermore", "additionally"]}, {"id": "q5", "type": "short_answer", "prompt": "The lecture was long. __________, it was very informative.", "points": 1, "acceptedAnswers": ["nevertheless", "however", "still"]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 1: Using Appropriate Cohesive Device';

update module_content mc
set data = '{"instructions": "Directions: Combine the following sentences into one using an appropriate cohesive device.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "The project was challenging. We completed it successfully.", "points": 1, "acceptedAnswers": ["The project was challenging; however, we completed it successfully.", "The project was challenging, but we completed it successfully."]}, {"id": "q2", "type": "short_answer", "prompt": "She was tired. She continued working.", "points": 1, "acceptedAnswers": ["She was tired; nevertheless, she continued working.", "Although she was tired, she continued working."]}, {"id": "q3", "type": "short_answer", "prompt": "It rained heavily. The game was canceled.", "points": 1, "acceptedAnswers": ["It rained heavily; therefore, the game was canceled.", "It rained heavily, so the game was canceled."]}, {"id": "q4", "type": "short_answer", "prompt": "He didn''t study for the test. He failed.", "points": 1, "acceptedAnswers": ["He didn''t study for the test, so he failed."]}, {"id": "q5", "type": "short_answer", "prompt": "I woke up late. I missed the bus.", "points": 1, "acceptedAnswers": ["I woke up late; as a result, I missed the bus.", "I woke up late, so I missed the bus."]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 2: Sentence Linking';

update module_content mc
set data = '{"instructions": "Directions: Reconstruct the scrambled sentences into a cohesive paragraph. Use cohesive devices to connect them.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Set 1 — a. We assigned roles based on each member''s strength. b. We were given a week to finish our final project. c. Everyone gave their best effort. d. As a result, we completed the task on time.", "points": 2, "acceptedAnswers": ["We were given a week to finish our final project. We assigned roles based on each member''s strength. Everyone gave their best effort. As a result, we completed the task on time."]}, {"id": "q2", "type": "short_answer", "prompt": "Set 2 — a. We reviewed the presentation several times. b. Our group was assigned to present the topic in class. c. We corrected the parts that needed improvement. d. Therefore, we were able to deliver the presentation confidently.", "points": 2, "acceptedAnswers": ["Our group was assigned to present the topic in class. We reviewed the presentation several times. We corrected the parts that needed improvement. Therefore, we were able to deliver the presentation confidently."]}, {"id": "q3", "type": "short_answer", "prompt": "Set 3 — a. She practiced speaking English with her classmates. b. She became more confident in expressing her ideas. c. She initially felt nervous when speaking in front of the class. d. As a result, she participated more actively in class discussions.", "points": 2, "acceptedAnswers": ["She initially felt nervous when speaking in front of the class. She practiced speaking English with her classmates. She became more confident in expressing her ideas. As a result, she participated more actively in class discussions."]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 3: Paragraph Reconstruction';

update module_content mc
set data = '{"instructions": "Directions: Write a paragraph (6–8 sentences) about \"An Unforgettable School Experience\" using at least five different cohesive devices.", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Write your paragraph here.", "points": 8, "sampleAnswer": "Last year, our class joined a regional quiz bee, and it turned out to be an unforgettable experience. At first, I was nervous because the competition included top schools in the region. However, our team practiced every day after class to prepare. As we studied together, we also became closer as friends. During the competition, we faced difficult questions, but we stayed calm and supported each other. In addition, our coach reminded us to trust our preparation. As a result, we placed among the top three teams. Because of that experience, I learned that teamwork and preparation can help us overcome even the most challenging situations."}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Activity 4: Cohesion Review Writing Task';

update module_content mc
set data = '{"instructions": "Directions: Read each question carefully and choose the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "What is the main focus of discourse unity?", "points": 1, "options": ["Spelling", "Staying on a single topic", "Word choice", "Synonyms"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "Which of the following is a cohesive device?", "points": 1, "options": ["Test", "Page", "However", "Topic"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "What makes a paragraph unified?", "points": 1, "options": ["Use of headings", "Use of transition words only", "It discusses one idea clearly.", "All sentences are questions."], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Which sentence uses a cohesive device?", "points": 1, "options": ["\"The class ended.\"", "\"The class ended. After that, we went to lunch.\"", "\"We are done.\"", "\"The subject was Math.\""], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Which is the best way to show contrast?", "points": 1, "options": ["Moreover", "Furthermore", "However", "Next"], "correctIndex": 2}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 3: Discourse Competence'
  and mc.title = 'Self-Check & Reflection';

update module_content mc
set data = '{"instructions": "Directions: Each sentence describes an item without naming it. Name the item being described.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "It''s a tool for cutting paper.", "points": 1, "acceptedAnswers": ["scissors"]}, {"id": "q2", "type": "short_answer", "prompt": "It''s a machine where you print documents.", "points": 1, "acceptedAnswers": ["printer"]}, {"id": "q3", "type": "short_answer", "prompt": "It''s a long seat for many students in class.", "points": 1, "acceptedAnswers": ["bench"]}, {"id": "q4", "type": "short_answer", "prompt": "It''s the place where the teacher writes.", "points": 1, "acceptedAnswers": ["whiteboard", "blackboard", "chalkboard", "board"]}, {"id": "q5", "type": "short_answer", "prompt": "It''s a flat item you write on.", "points": 1, "acceptedAnswers": ["paper", "notebook"]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 1: Describe Without Naming';

update module_content mc
set data = '{"instructions": "Directions: Replace the __underlined__ word with a near-equivalent word or expression that has a similar meaning, appropriate to the context.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "I need to __copy__ this document.", "points": 1, "acceptedAnswers": ["reproduce", "duplicate"]}, {"id": "q2", "type": "short_answer", "prompt": "Please __answer__ this question.", "points": 1, "acceptedAnswers": ["respond", "respond to", "reply", "reply to"]}, {"id": "q3", "type": "short_answer", "prompt": "Can you __fix__ my computer?", "points": 1, "acceptedAnswers": ["repair"]}, {"id": "q4", "type": "short_answer", "prompt": "She''s wearing __shoes__.", "points": 1, "acceptedAnswers": ["footwear"]}, {"id": "q5", "type": "short_answer", "prompt": "We will __talk__ later.", "points": 1, "acceptedAnswers": ["speak", "chat", "discuss"]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 2: Near-Equivalent Expressions';

update module_content mc
set data = '{"instructions": "Directions: Complete the conversation using approximation, then write your own 4-turn dialogue using the same strategy.\n\nStudent A: \"Do you have that thing for slicing paper?\"\nStudent B: \"You mean the __________?\"\nStudent A: \"Yes, the sharp tool with handles.\"\nStudent B: \"Oh, you mean the __________. Here it is.\"", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Fill in both blanks (they are the same word).", "points": 1, "acceptedAnswers": ["scissors"]}, {"id": "q2", "type": "short_answer", "subjective": true, "prompt": "Task: Write a 4-turn dialogue in which you ask about an object that you cannot name directly. Use approximation to describe the object.", "points": 3, "sampleAnswer": "Student A: \"Can you hand me the thing we use to hold papers together?\" Student B: \"You mean the little metal clip?\" Student A: \"Yes, the small clip you press to open.\" Student B: \"Oh, you mean the paper clip. Here it is.\""}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 3: Simulated Conversation Prompt';

update module_content mc
set data = '{"instructions": "Directions: This activity works well with a partner, but you can also do it on your own. Choose three objects commonly found at home, in school, or in the community. For each one, describe it (using its function, appearance, size, location, or purpose) without saying its name — as if explaining it to someone who has to guess what it is. Then answer the reflection question below.", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Reflection: How did approximation help you communicate when you could not directly name the object?", "points": 2, "sampleAnswer": "Approximation helped me keep the conversation going even when I forgot the exact word. By describing the object''s function and appearance, my partner could still understand what I meant, which showed me that communication can continue even with limited vocabulary."}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 4: Guess the Object (Peer Activity)';

update module_content mc
set data = '{"instructions": "Directions: Rephrase the following broken or unclear sentences.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "\"Him absent again today.\"", "points": 1, "acceptedAnswers": ["He is absent again today."]}, {"id": "q2", "type": "short_answer", "prompt": "\"No understand topic.\"", "points": 1, "acceptedAnswers": ["I didn''t understand the topic.", "I don''t understand the topic."]}, {"id": "q3", "type": "short_answer", "prompt": "\"Project late submit.\"", "points": 1, "acceptedAnswers": ["The project was submitted late."]}, {"id": "q4", "type": "short_answer", "prompt": "\"Test hard, not review.\"", "points": 1, "acceptedAnswers": ["The test was difficult because I didn''t review.", "The test was hard because I didn''t review."]}, {"id": "q5", "type": "short_answer", "prompt": "\"I busy, later talk.\"", "points": 1, "acceptedAnswers": ["I''m busy right now. Let''s talk later.", "I''m busy right now; let''s talk later."]}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 1: Rephrasing for Clarity';

update module_content mc
set data = '{"instructions": "Directions: Below is a series of broken or informal chat messages. Choose the best revised version from the options provided.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Original: \"U submit? Not yet why? Prof say submit now.\"", "points": 1, "options": ["You submit already? Why no? The prof want now.", "Have you submitted? Not yet? The professor said we should submit now.", "Submit done? Why late? Teacher ask now.", "Prof say submit, u submit not yet why?"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "Original: \"Me no idea what to do. U done?\"", "points": 1, "options": ["I don''t know what doing. You finished?", "Me confused. Are you doing?", "I have no idea what to do. Have you finished?", "No clue what to do, did you?"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Original: \"Cant join meet. Net bad. Tell sir pls.\"", "points": 1, "options": ["I can''t join the meeting. My internet is bad. Please tell sir.", "Can''t join, net no good. Inform.", "Net bad join no. Tell teacher.", "Meeting no go. You tell?"], "correctIndex": 0}, {"id": "q4", "type": "multiple_choice", "prompt": "Original: \"Where link? U got it? Mine gone.\"", "points": 1, "options": ["Got link? My gone. Share please.", "Where is the link? Do you have it? I lost mine.", "U have the link, I no.", "Link? Mine deleted. Yours?"], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Original: \"Late again. She mad?\"", "points": 1, "options": ["I''m late again. Is she angry?", "Again late. She angry?", "She mad I late?", "Late again. She scold?"], "correctIndex": 0}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 2: Chat Message Repair';

update module_content mc
set data = '{"instructions": "Directions: Read each unclear or incomplete message. Rewrite it to make the meaning clear, complete, and appropriate for communication. You may add or rearrange words, but keep the original meaning. Answers may vary — your teacher will read and score them. Example — Original: \"Meeting tomorrow? What time again?\" Reconstructed: \"What time is our meeting tomorrow?\"", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "\"Need submit project today but printer no work.\"", "points": 1, "sampleAnswer": "I need to submit my project today, but the printer isn''t working."}, {"id": "q2", "type": "short_answer", "subjective": true, "prompt": "\"Can you send file? I cannot find mine.\"", "points": 1, "sampleAnswer": "Can you send me the file? I can''t find mine."}, {"id": "q3", "type": "short_answer", "subjective": true, "prompt": "\"Teacher said change it but I don''t know what part.\"", "points": 1, "sampleAnswer": "The teacher said to change it, but I don''t know which part."}, {"id": "q4", "type": "short_answer", "subjective": true, "prompt": "\"Sorry late reply. I was busy earlier.\"", "points": 1, "sampleAnswer": "Sorry for the late reply. I was busy earlier."}, {"id": "q5", "type": "short_answer", "subjective": true, "prompt": "\"Group meeting where? Library or classroom?\"", "points": 1, "sampleAnswer": "Where is the group meeting, the library or the classroom?"}, {"id": "q6", "type": "short_answer", "subjective": true, "prompt": "**Challenge:** Choose one of the reconstructed messages above and rewrite it as if you were sending it to a teacher or professor. Pay attention to clarity, politeness, and formality.", "points": 2, "sampleAnswer": "Good day, Sir/Ma''am. I would like to inform you that I need to submit my project today, but my printer is currently not working. I apologize for the inconvenience and will find another way to print it as soon as possible."}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 3: Fix the Message';

update module_content mc
set data = '{"instructions": "Directions: Think of a poorly constructed spoken message you have heard (for example, a rushed or informal voice message). Write it down, then write the corrected, reconstructed version of the message.", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Write the original message and your reconstructed version.", "points": 2, "sampleAnswer": "Original: \"Uy, meeting later ha, dun sa room, di ko sure kelan.\" Reconstructed: \"Hi, just a reminder that we have a meeting later in the usual room, though I''m not yet sure of the exact time.\""}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Activity 4: Listening and Message Reconstruction';

update module_content mc
set data = '{"instructions": "Directions: Read each question carefully and choose the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "What is approximation in strategic competence?", "points": 1, "options": ["Using exact words all the time", "Describing things without naming them directly", "Avoiding conversation", "Memorizing vocabulary lists"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "What should you do when you forget a word in English?", "points": 1, "options": ["Stop talking", "Say nothing", "Use a near-equivalent word", "Say \"I don''t know\" only"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Reconstruction is useful when:", "points": 1, "options": ["You want to memorize a speech", "You are taking a reading test", "You have to rephrase a confusing statement", "You don''t want to talk"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Which sentence shows correct reconstruction?", "points": 1, "options": ["\"No review, hard test.\"", "\"I didn''t review, so the test was hard.\"", "\"Review test no me.\"", "\"Test okay, but me not study.\""], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Which shows strategic competence?", "points": 1, "options": ["Using gestures to support speech", "Writing poetry only", "Memorizing grammar rules", "Reading silently"], "correctIndex": 0}]}'::jsonb
from modules m
where m.id = mc.module_id
  and m.title = 'Module 4: Strategic Competence'
  and mc.title = 'Self-Check & Reflection';


-- Any progress row already saved against a now-subjective question keeps
-- the score it was given; only new submissions are held for review. See
-- section 7 of add_subjective_review.sql, which backfills subjective_max
-- for those older rows so the totals still add up.
