-- ==========================================================
-- Learning Hub - Real course content seed
-- Module 3: Discourse Competence (Sections 3.1-3.2 + Self-Check)
-- Run AFTER schema.sql and seed.sql (needs faculty1@learninghub.local).
--
-- NOTE: the source document does not include an answer key.
-- Sequencing Exercise (3.1 Activity 2), the ✅/❌ unity checks (3.1
-- Activity 3), and the Self-Check multiple-choice items were graded
-- from the logic of each item; review and adjust in Module Builder
-- if an official key exists. Free-response items (paragraph writing,
-- sentence linking, paragraph reconstruction) grade by matching one
-- accepted sample answer, since the activity system checks short
-- answers exactly; treat those scores as a starting point.
-- ==========================================================

WITH mod3 AS (
  INSERT INTO modules (title, subject, description, teacher_id, status)
  VALUES (
    'Module 3: Discourse Competence',
    'English - Communicative Competence',
    'Areas of Focus: Unity and Cohesion.',
    (SELECT id FROM profiles WHERE email = 'faculty1@learninghub.local'),
    'approved'
  )
  RETURNING id
)
INSERT INTO module_content (module_id, order_index, type, title, data)
SELECT id, 0, 'lecture', 'Module 3: Discourse Competence – Overview', '{"body": "Discourse competence is an important component of effective communication because it involves organizing ideas and connecting them in a clear and meaningful way. It enables learners to produce spoken and written texts that are logical, organized, and easy to understand. Rather than expressing ideas as separate sentences, discourse competence helps speakers and writers connect their thoughts to form meaningful paragraphs, conversations, and longer texts.\n\nIn this module, you will explore two important aspects of discourse competence: unity and cohesion. Unity focuses on keeping ideas centered on a clear main topic, while cohesion involves using appropriate language devices to connect sentences and ideas. Developing these skills will help you organize your thoughts, maintain a clear focus, and communicate messages more effectively in academic, social, and everyday situations.\n\nLearning Outcomes\nAt the end of this module, you should be able to:\n1. demonstrate understanding of discourse competence and its role in organizing meaningful communication;\n2. identify the characteristics of unified paragraphs and texts that maintain a clear and focused main idea;\n3. use appropriate cohesive devices to connect ideas and sentences clearly and logically; and\n4. produce organized and coherent paragraphs that demonstrate unity and cohesion in written communication.", "readAloudEnabled": true}'::jsonb FROM mod3
UNION ALL SELECT id, 1, 'lecture', 'Section 3.1: Unity in Communication', '{"body": "Unity in discourse refers to the ability to organize ideas around a clear and central topic. A unified paragraph presents one main idea and includes supporting details that are directly related to it. In this section, you will explore how topic sentences, relevant supporting details, and logical organization help create unity in communication. You will practice identifying main ideas, arranging sentences in a logical order, determining whether details support a topic, and writing focused paragraphs. These skills will help you express your thoughts clearly and maintain focus when communicating in academic, social, and everyday situations.", "readAloudEnabled": true}'::jsonb FROM mod3
UNION ALL SELECT id, 2, 'activity', 'Activity 1: Topic Sentence Identification', '{"instructions": "Read each paragraph and identify the best topic sentence.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Paragraph 1: Studying in college can be challenging for many students, but time management is crucial for academic success. One way to manage your time effectively is by setting aside specific blocks of time for studying each day. It''s also helpful to avoid distractions, such as turning off your phone while studying. Balancing schoolwork with other commitments can help ensure you stay on top of your studies.", "points": 1, "options": ["College students must develop good time management skills.", "Time management helps balance schoolwork and personal life.", "College life is challenging without effective time management.", "Effective time management can lead to academic success."], "correctIndex": 3}, {"id": "q2", "type": "multiple_choice", "prompt": "Paragraph 2: Many students prefer to study at night when fewer people are around, and the campus is quieter. This can provide a peaceful environment where students can concentrate better. Additionally, for night owls, studying at night aligns with their natural productivity rhythms. On the other hand, others prefer morning study sessions when they feel more refreshed.", "points": 1, "options": ["Students tend to study at night to avoid distractions.", "Quiet study environments are preferred by many students.", "Studying at night can be more effective for some students.", "Night study sessions are preferred by some students for better concentration."], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Paragraph 3: Group projects in college are a great way for students to enhance their communication and collaboration skills. Working with peers allows students to share ideas, brainstorm solutions, and develop a deeper understanding of the subject matter. Additionally, group projects help students learn how to delegate tasks and manage deadlines. However, teamwork also requires patience and flexibility to ensure that everyone''s ideas are considered.", "points": 1, "options": ["Group projects enhance communication and teamwork skills.", "Students often struggle with collaboration during group projects.", "Working in groups is essential for academic success.", "Group projects help students improve collaboration and responsibility."], "correctIndex": 0}]}'::jsonb FROM mod3
UNION ALL SELECT id, 3, 'activity', 'Activity 2: Sequencing Exercise', '{"instructions": "Rearrange the sentences into a coherent paragraph. Choose the option with the correct order.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Item 1 — a. Finally, we presented our work confidently. b. We brainstormed ideas and selected the best one. c. The group project was a success. d. Everyone contributed during the research phase.", "points": 1, "options": ["c, b, d, a", "b, d, c, a", "d, b, a, c", "a, c, b, d"], "correctIndex": 0}, {"id": "q2", "type": "multiple_choice", "prompt": "Item 2 — a. I checked my backpack to make sure I had everything. b. I quickly got dressed and brushed my teeth. c. When the alarm rang, I jumped out of bed. d. Then I left for school.", "points": 1, "options": ["a, b, d, c", "c, b, d, a", "d, b, c, a", "a, c, b, d"], "correctIndex": 1}, {"id": "q3", "type": "multiple_choice", "prompt": "Item 3 — a. We all clapped and cheered as she crossed the finish line. b. Our classmate joined a local marathon last weekend. c. She trained for weeks to build her stamina. d. During the race, she kept a steady pace and didn''t give up.", "points": 1, "options": ["a, b, c, d", "c, b, d, a", "b, c, d, a", "b, d, c, a"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Item 4 — a. He turned off the lights and closed the door. b. After dinner, my dad washed the dishes. c. Then he watered the plants in the garden. d. When everything was done, he got ready for bed.", "points": 1, "options": ["c, b, a, d", "a, b, c, d", "d, c, b, a", "b, c, a, d"], "correctIndex": 3}, {"id": "q5", "type": "multiple_choice", "prompt": "Item 5 — a. Suddenly, it started to rain heavily. b. I grabbed my umbrella and ran to the bus stop. c. I was walking to school on a cloudy morning. d. I arrived just in time, soaking wet but safe.", "points": 1, "options": ["b, a, c, d", "c, a, b, d", "a, c, b, d", "c, b, a, d"], "correctIndex": 1}]}'::jsonb FROM mod3
UNION ALL SELECT id, 4, 'activity', 'Activity 3: Paragraph Unity Check', '{"instructions": "For each set, decide whether the sentence supports the given main idea. Mark True if it belongs, False if it does not.", "questions": [{"id": "q1", "type": "true_false", "prompt": "Main Idea: Watching movies — \"I enjoy watching movies.\"", "points": 1, "correctAnswer": true}, {"id": "q2", "type": "true_false", "prompt": "Main Idea: Watching movies — \"My favorite genres are comedy and action.\"", "points": 1, "correctAnswer": true}, {"id": "q3", "type": "true_false", "prompt": "Main Idea: Watching movies — \"Bananas are high in potassium.\"", "points": 1, "correctAnswer": false}, {"id": "q4", "type": "true_false", "prompt": "Main Idea: Using the internet for learning — \"The internet provides access to unlimited information.\"", "points": 1, "correctAnswer": true}, {"id": "q5", "type": "true_false", "prompt": "Main Idea: Using the internet for learning — \"Many students use it for research and school projects.\"", "points": 1, "correctAnswer": true}, {"id": "q6", "type": "true_false", "prompt": "Main Idea: Using the internet for learning — \"Reading books can improve vocabulary.\"", "points": 1, "correctAnswer": false}, {"id": "q7", "type": "true_false", "prompt": "Main Idea: Physical benefits of basketball — \"Basketball helps improve physical fitness.\"", "points": 1, "correctAnswer": true}, {"id": "q8", "type": "true_false", "prompt": "Main Idea: Physical benefits of basketball — \"Playing regularly builds endurance and coordination.\"", "points": 1, "correctAnswer": true}, {"id": "q9", "type": "true_false", "prompt": "Main Idea: Physical benefits of basketball — \"Math is my least favorite subject in school.\"", "points": 1, "correctAnswer": false}, {"id": "q10", "type": "true_false", "prompt": "Main Idea: Family birthday traditions — \"My family always celebrates birthdays with a special dinner.\"", "points": 1, "correctAnswer": true}, {"id": "q11", "type": "true_false", "prompt": "Main Idea: Family birthday traditions — \"We cook our favorite meals and invite close friends.\"", "points": 1, "correctAnswer": true}, {"id": "q12", "type": "true_false", "prompt": "Main Idea: Family birthday traditions — \"Mount Everest is the highest mountain in the world.\"", "points": 1, "correctAnswer": false}, {"id": "q13", "type": "true_false", "prompt": "Main Idea: Learning English — \"Learning English takes time and practice.\"", "points": 1, "correctAnswer": true}, {"id": "q14", "type": "true_false", "prompt": "Main Idea: Learning English — \"Speaking with native speakers helps improve fluency.\"", "points": 1, "correctAnswer": true}, {"id": "q15", "type": "true_false", "prompt": "Main Idea: Learning English — \"The Great Wall of China is a popular tourist attraction.\"", "points": 1, "correctAnswer": false}]}'::jsonb FROM mod3
UNION ALL SELECT id, 5, 'activity', 'Activity 4: Short Paragraph Writing', '{"instructions": "Write a 5-sentence paragraph on the topic: \"My experience in joining a student organization.\" Ensure unity by staying focused on one main idea.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Write your 5-sentence paragraph here.", "points": 5, "acceptedAnswers": ["Joining a student organization helped me grow as a person. I learned how to manage my time between academics and extracurricular activities. I also built new friendships with members who shared the same interests. Through the organization''s projects, I developed leadership and communication skills. Overall, being part of the organization made my college experience more meaningful."]}]}'::jsonb FROM mod3
UNION ALL SELECT id, 6, 'lecture', 'Section 3.2: Cohesion through Language Devices', '{"body": "Cohesion refers to the use of language devices that connect sentences and ideas within a text. In this section, you will explore how transition words, pronouns, conjunctions, and other cohesive devices help create smooth and logical connections between ideas. You will practice selecting appropriate cohesive devices, linking sentences, reconstructing paragraphs, and writing cohesive texts. Developing these skills will help you present your ideas in a clear, organized, and connected manner.", "readAloudEnabled": true}'::jsonb FROM mod3
UNION ALL SELECT id, 7, 'activity', 'Activity 1: Using Appropriate Cohesive Device', '{"instructions": "Choose the most appropriate cohesive device to complete each sentence.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "I studied hard for the test; __________, I got a high score.", "points": 1, "acceptedAnswers": ["as a result", "therefore", "consequently"]}, {"id": "q2", "type": "short_answer", "prompt": "The weather was bad; __________, we postponed the event.", "points": 1, "acceptedAnswers": ["therefore", "as a result", "so"]}, {"id": "q3", "type": "short_answer", "prompt": "I enjoy writing; __________, I''m not fond of reading.", "points": 1, "acceptedAnswers": ["however", "but"]}, {"id": "q4", "type": "short_answer", "prompt": "She is good at singing. __________, she can also play the guitar.", "points": 1, "acceptedAnswers": ["moreover", "furthermore", "in addition", "additionally"]}, {"id": "q5", "type": "short_answer", "prompt": "The lecture was long. __________, it was very informative.", "points": 1, "acceptedAnswers": ["however", "nevertheless", "still"]}]}'::jsonb FROM mod3
UNION ALL SELECT id, 8, 'activity', 'Activity 2: Sentence Linking', '{"instructions": "Combine the following sentences into one using an appropriate cohesive device.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "The project was challenging. We completed it successfully.", "points": 1, "acceptedAnswers": ["The project was challenging, but we completed it successfully."]}, {"id": "q2", "type": "short_answer", "prompt": "She was tired. She continued working.", "points": 1, "acceptedAnswers": ["Although she was tired, she continued working."]}, {"id": "q3", "type": "short_answer", "prompt": "It rained heavily. The game was canceled.", "points": 1, "acceptedAnswers": ["It rained heavily, so the game was canceled."]}, {"id": "q4", "type": "short_answer", "prompt": "He didn''t study for the test. He failed.", "points": 1, "acceptedAnswers": ["He didn''t study for the test, so he failed."]}, {"id": "q5", "type": "short_answer", "prompt": "I woke up late. I missed the bus.", "points": 1, "acceptedAnswers": ["I woke up late, so I missed the bus."]}]}'::jsonb FROM mod3
UNION ALL SELECT id, 9, 'activity', 'Activity 3: Paragraph Reconstruction', '{"instructions": "Reconstruct the scrambled sentences into a cohesive paragraph. Use cohesive devices to connect them.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Set 1 — a. We assigned roles based on each member''s strength. b. We were given a week to finish our final project. c. Everyone gave their best effort. d. As a result, we completed the task on time.", "points": 2, "acceptedAnswers": ["We were given a week to finish our final project. We assigned roles based on each member''s strength. Everyone gave their best effort. As a result, we completed the task on time."]}, {"id": "q2", "type": "short_answer", "prompt": "Set 2 — a. We reviewed the presentation several times. b. Our group was assigned to present the topic in class. c. We corrected the parts that needed improvement. d. Therefore, we were able to deliver the presentation confidently.", "points": 2, "acceptedAnswers": ["Our group was assigned to present the topic in class. We reviewed the presentation several times. We corrected the parts that needed improvement. Therefore, we were able to deliver the presentation confidently."]}, {"id": "q3", "type": "short_answer", "prompt": "Set 3 — a. She practiced speaking English with her classmates. b. She became more confident in expressing her ideas. c. She initially felt nervous when speaking in front of the class. d. As a result, she participated more actively in class discussions.", "points": 2, "acceptedAnswers": ["She initially felt nervous when speaking in front of the class. She practiced speaking English with her classmates. She became more confident in expressing her ideas. As a result, she participated more actively in class discussions."]}]}'::jsonb FROM mod3
UNION ALL SELECT id, 10, 'activity', 'Activity 4: Cohesion Review Writing Task', '{"instructions": "Write a paragraph (6–8 sentences) about \"An Unforgettable School Experience\" using at least five different cohesive devices.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Write your paragraph here.", "points": 8, "acceptedAnswers": ["Last year, our class joined a regional quiz bee, and it turned out to be an unforgettable experience. At first, I was nervous because the competition included top schools in the region. However, our team practiced every day after class to prepare. As we studied together, we also became closer as friends. During the competition, we faced difficult questions, but we stayed calm and supported each other. In addition, our coach reminded us to trust our preparation. As a result, we placed among the top three teams. Because of that experience, I learned that teamwork and preparation can help us overcome even the most challenging situations."]}]}'::jsonb FROM mod3
UNION ALL SELECT id, 11, 'activity', 'Self-Check & Reflection', '{"instructions": "Read each question carefully and choose the letter of the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "What is the main focus of discourse unity?", "points": 1, "options": ["Spelling", "Staying on a single topic", "Word choice", "Synonyms"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "Which of the following is a cohesive device?", "points": 1, "options": ["Test", "Page", "However", "Topic"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "What makes a paragraph unified?", "points": 1, "options": ["Use of headings", "Use of transition words only", "It discusses one idea clearly.", "All sentences are questions."], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Which sentence uses a cohesive device?", "points": 1, "options": ["\"The class ended.\"", "\"The class ended. After that, we went to lunch.\"", "\"We are done.\"", "\"The subject was Math.\""], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Which is the best way to show contrast?", "points": 1, "options": ["Moreover", "Furthermore", "However", "Next"], "correctIndex": 2}]}'::jsonb FROM mod3
UNION ALL SELECT id, 12, 'lecture', 'Reflection, Optional Task & Closing', '{"body": "Reflection Prompt: How has learning about unity and cohesion improved the way you organize your thoughts in writing or speaking?\n\nOptional Task: Submit a video or journal entry where you describe a time you struggled with writing or expressing yourself—and how you overcame it using cohesive devices.\n\nClosing Section\nCongratulations! You''ve completed the modules designed to boost your communicative competence. Continue practicing and exploring ways to use English in meaningful, real-world situations!", "readAloudEnabled": true}'::jsonb FROM mod3;
