-- ==========================================================
-- Learning Hub - Real course content seed
-- Module 4: Strategic Competence (Sections 4.1-4.2 + Self-Check)
-- Run AFTER schema.sql and seed.sql (needs faculty1@learninghub.local).
--
-- NOTE: the source document does not include an answer key.
-- Activity 2 (4.2) "Chat Message Repair" answers were inferred as
-- the most grammatically correct and polite revision of each item;
-- Self-Check answers were inferred from context. Review and adjust
-- in Module Builder if an official key exists. Free-response items
-- (descriptions, near-equivalents, dialogues, rephrasing, paragraph
-- writing) grade by matching one accepted sample answer, since the
-- activity system checks short answers exactly; treat those scores
-- as a starting point. Activity 4 of 4.1 ("Guess the Object") is a
-- partner activity — it is seeded as a single reflection question,
-- since the guessing itself happens live between students. Likewise
-- Activity 4 of 4.2 depends on an audio clip that isn''t part of this
-- platform, so it is seeded as an open-ended writing prompt instead.
-- The Teacher''s Guide and Assessment Rubric from the source document
-- are included as a reference lecture block at the end of the module.
-- ==========================================================

WITH mod4 AS (
  INSERT INTO modules (title, subject, description, teacher_id, status)
  VALUES (
    'Module 4: Strategic Competence',
    'English - Communicative Competence',
    'Areas in Focus: Approximation and Reconstruction.',
    (SELECT id FROM profiles WHERE email = 'faculty1@learninghub.local'),
    'approved'
  )
  RETURNING id
)
INSERT INTO module_content (module_id, order_index, type, title, data)
SELECT id, 0, 'lecture', 'Module 4: Strategic Competence – Overview', '{"body": "Strategic competence is an important component of communicative competence because it enables learners to manage communication difficulties and continue expressing their ideas when they experience gaps in language knowledge. During real-time communication, speakers may forget a word, encounter an unfamiliar expression, or have difficulty making a message clear. Strategic competence allows them to use alternative ways of communicating their intended meaning instead of stopping the interaction.\n\nIn this module, you will explore two important communication strategies: approximation and reconstruction. Approximation involves using a word or expression that is close in meaning to the intended word, while reconstruction involves rephrasing or restating a message to make its meaning clearer. Developing these strategies will help you remain engaged in conversations, clarify your ideas, and prevent communication breakdowns in academic, social, and everyday situations.\n\nLearning Outcomes\nAt the end of this module, you should be able to:\n1. demonstrate understanding of strategic competence and its role in maintaining effective communication;\n2. identify appropriate approximation strategies when the exact word or expression is unavailable;\n3. use reconstruction strategies to clarify, rephrase, and restate unclear or incomplete messages; and\n4. apply approximation and reconstruction strategies to maintain clear and effective communication in meaningful situations.", "readAloudEnabled": true}'::jsonb FROM mod4
UNION ALL SELECT id, 1, 'lecture', 'Section 4.1: Approximation Strategies', '{"body": "Approximation is a communication strategy used when a speaker does not know, cannot remember, or cannot immediately retrieve the exact word needed to express an idea. Instead of stopping the conversation, the speaker uses a word or expression that is close in meaning or describes the object, function, appearance, or purpose. For example, a learner who cannot remember the word \"knife\" may describe it as \"something used for slicing.\"\n\nIn this section, you will explore how approximation can help you communicate your intended meaning even when the exact vocabulary is unavailable. You will practice describing objects without naming them, replacing words with near-equivalent expressions, and using approximation in short conversations. These skills will help you maintain fluency, express ideas, and avoid communication breakdowns during real-time communication.", "readAloudEnabled": true}'::jsonb FROM mod4
UNION ALL SELECT id, 2, 'activity', 'Activity 1: Describe Without Naming', '{"instructions": "Each sentence describes an item without naming it. Name the item being described.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "It''s a tool for cutting paper.", "points": 1, "acceptedAnswers": ["scissors"]}, {"id": "q2", "type": "short_answer", "prompt": "It''s a machine where you print documents.", "points": 1, "acceptedAnswers": ["printer"]}, {"id": "q3", "type": "short_answer", "prompt": "It''s a long seat for many students in class.", "points": 1, "acceptedAnswers": ["bench"]}, {"id": "q4", "type": "short_answer", "prompt": "It''s the place where the teacher writes.", "points": 1, "acceptedAnswers": ["blackboard", "whiteboard", "chalkboard", "board"]}, {"id": "q5", "type": "short_answer", "prompt": "It''s a flat item you write on.", "points": 1, "acceptedAnswers": ["paper", "notebook", "desk"]}]}'::jsonb FROM mod4
UNION ALL SELECT id, 3, 'activity', 'Activity 2: Near-Equivalent Expressions', '{"instructions": "Replace the bolded word with a near-equivalent word or expression that has a similar meaning, appropriate to the context.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "I need to copy this document.", "points": 1, "acceptedAnswers": ["duplicate", "reproduce"]}, {"id": "q2", "type": "short_answer", "prompt": "Please answer this question.", "points": 1, "acceptedAnswers": ["respond to", "reply to"]}, {"id": "q3", "type": "short_answer", "prompt": "Can you fix my computer?", "points": 1, "acceptedAnswers": ["repair"]}, {"id": "q4", "type": "short_answer", "prompt": "She''s wearing shoes.", "points": 1, "acceptedAnswers": ["footwear"]}, {"id": "q5", "type": "short_answer", "prompt": "We will talk later.", "points": 1, "acceptedAnswers": ["chat", "discuss", "speak"]}]}'::jsonb FROM mod4
UNION ALL SELECT id, 4, 'activity', 'Activity 3: Simulated Conversation Prompt', '{"instructions": "Complete the conversation using approximation, then write your own 4-turn dialogue using the same strategy.\n\nStudent A: \"Do you have that thing for slicing paper?\"\nStudent B: \"You mean the __________?\"\nStudent A: \"Yes, the sharp tool with handles.\"\nStudent B: \"Oh, you mean the __________. Here it is.\"", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Fill in both blanks (they are the same word).", "points": 1, "acceptedAnswers": ["scissors"]}, {"id": "q2", "type": "short_answer", "prompt": "Task: Write a 4-turn dialogue in which you ask about an object that you cannot name directly. Use approximation to describe the object.", "points": 3, "acceptedAnswers": ["Student A: \"Can you hand me the thing we use to hold papers together?\"\nStudent B: \"You mean the little metal clip?\"\nStudent A: \"Yes, the small clip you press to open.\"\nStudent B: \"Oh, you mean the paper clip. Here it is.\""]}]}'::jsonb FROM mod4
UNION ALL SELECT id, 5, 'activity', 'Activity 4: Guess the Object (Peer Activity)', '{"instructions": "This is a partner activity: choose an object commonly found at home, in school, or in the community, and describe it to a partner (using its function, appearance, size, location, or purpose) without saying its name, until your partner guesses it. Do this for three different objects, then answer the reflection question below.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Reflection: How did approximation help you communicate when you could not directly name the object?", "points": 2, "acceptedAnswers": ["Approximation helped me keep the conversation going even when I forgot the exact word. By describing the object''s function and appearance, my partner could still understand what I meant, which showed me that communication can continue even with limited vocabulary."]}]}'::jsonb FROM mod4
UNION ALL SELECT id, 6, 'lecture', 'Section 4.2: Reconstruction Strategies', '{"body": "Reconstruction is a communication strategy used to clarify a message by rephrasing or restating an idea when the original message is unclear, incomplete, or misunderstood. Instead of repeating the same statement, the speaker changes the wording while maintaining the intended meaning. For example, \"Please submit the file before the scheduled time\" can be reconstructed as \"Please send your file before the deadline.\"\n\nIn this section, you will explore how reconstruction can be used to make messages clearer and more appropriate for different communication situations. You will practice rephrasing unclear statements, repairing informal or incomplete messages, and rewriting messages for clearer communication. These skills will help you clarify meaning, prevent misunderstandings, and maintain effective interaction in academic, social, and online communication.", "readAloudEnabled": true}'::jsonb FROM mod4
UNION ALL SELECT id, 7, 'activity', 'Activity 1: Rephrasing for Clarity', '{"instructions": "Rephrase the following broken or unclear sentences.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "\"Him absent again today.\"", "points": 1, "acceptedAnswers": ["He is absent again today."]}, {"id": "q2", "type": "short_answer", "prompt": "\"No understand topic.\"", "points": 1, "acceptedAnswers": ["I don''t understand the topic."]}, {"id": "q3", "type": "short_answer", "prompt": "\"Project late submit.\"", "points": 1, "acceptedAnswers": ["The project was submitted late."]}, {"id": "q4", "type": "short_answer", "prompt": "\"Test hard, not review.\"", "points": 1, "acceptedAnswers": ["The test was hard because I didn''t review."]}, {"id": "q5", "type": "short_answer", "prompt": "\"I busy, later talk.\"", "points": 1, "acceptedAnswers": ["I''m busy right now; let''s talk later."]}]}'::jsonb FROM mod4
UNION ALL SELECT id, 8, 'activity', 'Activity 2: Chat Message Repair', '{"instructions": "Below is a series of broken or informal chat messages. Choose the best revised version from the options provided.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Original: \"U submit? Not yet why? Prof say submit now.\"", "points": 1, "options": ["You submit already? Why no? The prof want now.", "Have you submitted? Not yet? The professor said we should submit now.", "Submit done? Why late? Teacher ask now.", "Prof say submit, u submit not yet why?"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "Original: \"Me no idea what to do. U done?\"", "points": 1, "options": ["I don''t know what doing. You finished?", "Me confused. Are you doing?", "I have no idea what to do. Have you finished?", "No clue what to do, did you?"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Original: \"Cant join meet. Net bad. Tell sir pls.\"", "points": 1, "options": ["I can''t join the meeting. My internet is bad. Please tell sir.", "Can''t join, net no good. Inform.", "Net bad join no. Tell teacher.", "Meeting no go. You tell?"], "correctIndex": 0}, {"id": "q4", "type": "multiple_choice", "prompt": "Original: \"Where link? U got it? Mine gone.\"", "points": 1, "options": ["Got link? My gone. Share please.", "Where is the link? Do you have it? I lost mine.", "U have the link, I no.", "Link? Mine deleted. Yours?"], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Original: \"Late again. She mad?\"", "points": 1, "options": ["I''m late again. Is she angry?", "Again late. She angry?", "She mad I late?", "Late again. She scold?"], "correctIndex": 0}]}'::jsonb FROM mod4
UNION ALL SELECT id, 9, 'activity', 'Activity 3: Fix the Message', '{"instructions": "Read each unclear or incomplete message. Rewrite it to make the meaning clear, complete, and appropriate for communication. You may add or rearrange words, but keep the original meaning. Example — Original: \"Meeting tomorrow? What time again?\" Reconstructed: \"What time is our meeting tomorrow?\"", "questions": [{"id": "q1", "type": "short_answer", "prompt": "\"Need submit project today but printer no work.\"", "points": 1, "acceptedAnswers": ["I need to submit my project today, but the printer isn''t working."]}, {"id": "q2", "type": "short_answer", "prompt": "\"Can you send file? I cannot find mine.\"", "points": 1, "acceptedAnswers": ["Can you send me the file? I can''t find mine."]}, {"id": "q3", "type": "short_answer", "prompt": "\"Teacher said change it but I don''t know what part.\"", "points": 1, "acceptedAnswers": ["The teacher said to change it, but I don''t know which part."]}, {"id": "q4", "type": "short_answer", "prompt": "\"Sorry late reply. I was busy earlier.\"", "points": 1, "acceptedAnswers": ["Sorry for the late reply. I was busy earlier."]}, {"id": "q5", "type": "short_answer", "prompt": "\"Group meeting where? Library or classroom?\"", "points": 1, "acceptedAnswers": ["Where is the group meeting, the library or the classroom?"]}, {"id": "q6", "type": "short_answer", "prompt": "Challenge: Choose one of the reconstructed messages above and rewrite it as if you were sending it to a teacher or professor. Pay attention to clarity, politeness, and formality.", "points": 2, "acceptedAnswers": ["Good day, Sir/Ma''am. I would like to inform you that I need to submit my project today, but my printer is currently not working. I apologize for the inconvenience and will find another way to print it as soon as possible."]}]}'::jsonb FROM mod4
UNION ALL SELECT id, 10, 'activity', 'Activity 4: Listening and Message Reconstruction', '{"instructions": "Think of a poorly constructed spoken message you have heard (for example, a rushed or informal voice message). Write it down, then write the corrected, reconstructed version of the message.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Write the original message and your reconstructed version.", "points": 2, "acceptedAnswers": ["Original: \"Uy, meeting later ha, dun sa room, di ko sure kelan.\" Reconstructed: \"Hi, just a reminder that we have a meeting later in the usual room, though I''m not yet sure of the exact time.\""]}]}'::jsonb FROM mod4
UNION ALL SELECT id, 11, 'activity', 'Self-Check & Reflection', '{"instructions": "Read each question carefully and choose the letter of the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "What is approximation in strategic competence?", "points": 1, "options": ["Using exact words all the time", "Describing things without naming them directly", "Avoiding conversation", "Memorizing vocabulary lists"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "What should you do when you forget a word in English?", "points": 1, "options": ["Stop talking", "Say nothing", "Use a near-equivalent word", "Say \"I don''t know\" only"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Reconstruction is useful when:", "points": 1, "options": ["You want to memorize a speech", "You are taking a reading test", "You have to rephrase a confusing statement", "You don''t want to talk"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Which sentence shows correct reconstruction?", "points": 1, "options": ["\"No review, hard test.\"", "\"I didn''t review, so the test was hard.\"", "\"Review test no me.\"", "\"Test okay, but me not study.\""], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Which shows strategic competence?", "points": 1, "options": ["Using gestures to support speech", "Writing poetry only", "Memorizing grammar rules", "Reading silently"], "correctIndex": 0}]}'::jsonb FROM mod4
UNION ALL SELECT id, 12, 'lecture', 'Reflection, Optional Task & Closing', '{"body": "Reflection Prompt: Think of a time when you struggled to express yourself in English. What strategy did you use to keep the conversation going?\n\nOptional Task: Create a voice recording or write a short story about a time you used approximation or rephrasing to communicate your thoughts more clearly.\n\nClosing Section\nCongratulations! You''ve completed the modules designed to boost your communicative competence. Continue practicing and exploring ways to use English in meaningful, real-world situations!", "readAloudEnabled": true}'::jsonb FROM mod4
UNION ALL SELECT id, 13, 'lecture', 'Reference: Teacher''s Guide & Assessment Rubric', '{"body": "TEACHER''S GUIDE\n\nOverview: This teacher''s guide supports the implementation of the supplementary material designed to enhance communicative competence among Filipino L2 college freshmen. It outlines instructional strategies, tips for facilitation, suggested pacing, and tools for feedback.\n\nLearning Delivery Tips\n- Use each module as a weekly focus across a 4-week span.\n- Facilitate discussions before each activity using the mini-lessons.\n- Allow students to access modules asynchronously but require participation in feedback tasks or video reflection.\n- Convert self-check quizzes into auto-graded assessments (already done for you in this platform).\n\nSuggested Timeline\n- Week 1: Module 1 – Linguistic Competence\n- Week 2: Module 2 – Sociolinguistic Competence\n- Week 3: Module 3 – Discourse Competence\n- Week 4: Module 4 – Strategic Competence\n\nSuggested Grouping of Learners\n- Small peer groups for collaborative dialogue and reconstruction tasks\n- Individual for writing, quizzes, and reflection tasks\n\nFacilitator''s Role\n- Guide discussions around sociolinguistic and discourse norms\n- Encourage approximation and reformulation without judgment\n- Monitor use of cohesive devices and unity in output tasks\n\nASSESSMENT RUBRIC — For Performance-Based Tasks\nUse this rubric to evaluate dialogue building tasks, paragraph and reflection writing, and approximation/reconstruction exercises.\n\nLanguage Appropriateness\n- Excellent (4): Uses highly context-appropriate expressions throughout\n- Good (3): Generally uses appropriate expressions\n- Satisfactory (2): Some errors in appropriateness\n- Needs Improvement (1): Many expressions are not context-appropriate\n\nTask Completion\n- Excellent (4): All elements fully addressed and complete\n- Good (3): Most elements complete\n- Satisfactory (2): Some parts missing\n- Needs Improvement (1): Incomplete response\n\nAccuracy and Clarity\n- Excellent (4): Sentences are accurate and ideas clearly expressed\n- Good (3): Minor errors but meaning is clear\n- Satisfactory (2): Errors affect clarity in some parts\n- Needs Improvement (1): Errors significantly affect clarity\n\nUse of Strategy (Approximation/Reconstruction)\n- Excellent (4): Skillfully applies strategy (e.g., rephrasing, approximation)\n- Good (3): Applies strategy with some effectiveness\n- Satisfactory (2): Attempts but lacks fluency\n- Needs Improvement (1): Rare or no use of strategy\n\nCoherence and Organization\n- Excellent (4): Well-organized, logical flow of ideas\n- Good (3): Mostly organized, minor issues in flow\n- Satisfactory (2): Inconsistent organization\n- Needs Improvement (1): Disorganized or lacks logical flow", "readAloudEnabled": false}'::jsonb FROM mod4;
