-- ==========================================================
-- Learning Hub - Real course content seed
-- Module 2: Sociolinguistic Competence (Section 2.1 + Self-Check)
-- Run AFTER schema.sql and seed.sql (needs faculty1@learninghub.local).
--
-- Answer keys in this file follow the official "Final References and
-- Key to Correction" document. Questions the key records as "Answers
-- may vary" carry "subjective": true — the app does not auto-score
-- them; they are held for the teacher to read and score (see
-- add_subjective_review.sql), with the key's model answer kept in
-- "sampleAnswer" for the review screen.
-- ==========================================================

WITH mod2 AS (
  INSERT INTO modules (title, subject, description, teacher_id, status, sequence_order)
  VALUES (
    'Module 2: Sociolinguistic Competence',
    'English - Communicative Competence',
    'Area of Focus: Linguistic Realization.',
    (SELECT id FROM profiles WHERE email = 'faculty1@learninghub.local'),
    'approved',
    2
  )
  RETURNING id
)
INSERT INTO module_content (module_id, order_index, type, title, data)
SELECT id, 0, 'lecture', 'Module 2: Sociolinguistic Competence – Overview', '{"body": "Sociolinguistic competence is an important component of effective communication. It refers to the ability to use language appropriately according to the social and communicative context. It involves understanding that the way we communicate may change depending on who we are talking to, the situation, the purpose of the interaction, and the relationship between the speakers. In this module, you will explore how language choices, including vocabulary, expressions, formality, politeness, and tone, can vary across different academic, social, and everyday situations. Developing sociolinguistic competence will help you communicate ideas clearly and appropriately while showing respect for others and being sensitive to the social and cultural context of communication.\n\nLearning Outcomes\nAt the end of this module, you should be able to:\n1. demonstrate understanding of sociolinguistic competence and the role of context in language use;\n2. distinguish between formal and informal expressions appropriate for different social and communicative situations;\n3. use appropriate language, politeness, tone, and culturally sensitive expressions in academic, social, and everyday interactions; and\n4. create context-appropriate expressions and dialogues that demonstrate effective and socially appropriate communication.", "readAloudEnabled": true}'::jsonb FROM mod2
UNION ALL SELECT id, 1, 'lecture', 'Section 2.1: Linguistic Realization in Varying Contexts', '{"body": "Linguistic realization is an important part of effective communication. It involves choosing appropriate grammatical forms, vocabulary, expressions, and levels of formality based on the communicative situation. In this section, you will explore how language changes depending on who you are communicating with, where the interaction takes place, and what you want to communicate. You will practice using formal and informal expressions, polite language, and context-appropriate vocabulary in academic, social, and everyday situations. These skills will help you communicate your ideas clearly and respectfully while considering the social relationship and cultural expectations of the people you interact with.", "readAloudEnabled": true}'::jsonb FROM mod2
UNION ALL SELECT id, 2, 'activity', 'Activity 1: Expression Recasting', '{"instructions": "Directions: Recast each informal sentence into a more context-appropriate expression.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Recast: \u201cWhat time are you coming?\u201d", "points": 1, "acceptedAnswers": ["What time will you arrive?", "What time will you be arriving?"]}, {"id": "q2", "type": "short_answer", "prompt": "Recast: \u201cI\u2019m late. Wait a sec.\u201d", "points": 1, "acceptedAnswers": ["I apologize, I will be there shortly.", "I apologize for being late; please wait a moment."]}, {"id": "q3", "type": "short_answer", "prompt": "Recast: \u201cI don\u2019t know anything about that.\u201d", "points": 1, "acceptedAnswers": ["I''m not familiar with that topic.", "I\u2019m not familiar with that topic.", "I\u2019m not familiar with that, unfortunately."]}, {"id": "q4", "type": "short_answer", "prompt": "Recast: \u201cWhy didn\u2019t he come?\u201d", "points": 1, "acceptedAnswers": ["Do you know why he was absent?", "May I ask why he was unable to attend?"]}, {"id": "q5", "type": "short_answer", "prompt": "Recast: \u201cMan, the test was so hard!\u201d", "points": 1, "acceptedAnswers": ["The test was quite challenging.", "The examination was quite challenging."]}]}'::jsonb FROM mod2
UNION ALL SELECT id, 3, 'activity', 'Activity 2: Writing Formal and Informal Expressions', '{"instructions": "Directions: Write both a formal and an informal version of each situation below. Answers may vary — your teacher will read and score these.", "questions": [{"id": "q1f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Inviting a classmate to group work", "points": 1, "sampleAnswer": "Would you like to join our group for this activity?"}, {"id": "q1i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Inviting a classmate to group work", "points": 1, "sampleAnswer": "Hey, wanna join our group?"}, {"id": "q2f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Asking a teacher to extend a deadline", "points": 1, "sampleAnswer": "Would it be possible to request a short extension for the deadline?"}, {"id": "q2i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Asking a teacher to extend a deadline", "points": 1, "sampleAnswer": "Can I have a bit more time to pass this?"}, {"id": "q3f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Apologizing for being late", "points": 1, "sampleAnswer": "I apologize for arriving late."}, {"id": "q3i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Apologizing for being late", "points": 1, "sampleAnswer": "Sorry, I''m late!"}, {"id": "q4f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Congratulating a classmate", "points": 1, "sampleAnswer": "Congratulations on your achievement."}, {"id": "q4i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Congratulating a classmate", "points": 1, "sampleAnswer": "Nice job, congrats!"}, {"id": "q5f", "type": "short_answer", "subjective": true, "prompt": "**Formal:** Giving feedback on a peer''s work", "points": 1, "sampleAnswer": "Your work was well done overall, though a few areas could be improved."}, {"id": "q5i", "type": "short_answer", "subjective": true, "prompt": "**Informal:** Giving feedback on a peer''s work", "points": 1, "sampleAnswer": "Pretty good, but you could tweak a few parts."}]}'::jsonb FROM mod2
UNION ALL SELECT id, 4, 'activity', 'Activity 3: Context Matching', '{"instructions": "Directions: Match the linguistic realization to the appropriate situation.", "questions": [{"id": "q1", "type": "matching", "prompt": "Match each situation to the appropriate expression.", "points": 5, "pairs": [{"left": "Asking a friend casually", "right": "\u201cBro, do you need help?\u201d"}, {"left": "Talking to a dean formally", "right": "\u201cGood evening, Dean. May I request a short appointment?\u201d"}, {"left": "Making an excuse to a teacher", "right": "\u201cMiss, I wasn\u2019t able to submit it earlier due to an emergency.\u201d"}, {"left": "Casual plan with a peer", "right": "\u201cDude, let\u2019s grab snacks!\u201d"}, {"left": "Clarifying something with a teacher", "right": "\u201cSir, may I clarify something about the lecture?\u201d"}]}]}'::jsonb FROM mod2
UNION ALL SELECT id, 5, 'activity', 'Activity 4: Contextual Expression Revision', '{"instructions": "Directions: Read each statement and decide whether it is appropriate or inappropriate for the given situation. If it is inappropriate, rewrite it using a more context-appropriate form, considering formality, politeness, vocabulary, and the relationship between the speakers. Your teacher will read and score your revisions.", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Situation: You are speaking to your professor after class. \"Hey, can you explain this part again?\"", "points": 1, "sampleAnswer": "Inappropriate. Revised: \"Professor, could you please explain this part again?\""}, {"id": "q2", "type": "short_answer", "subjective": true, "prompt": "Situation: You are messaging your close classmate about a group project. \"Good afternoon. I would like to inquire whether you have completed your assigned portion.\"", "points": 1, "sampleAnswer": "Inappropriate (too formal). Revised: \"Hi! Have you finished your part of the group project?\""}, {"id": "q3", "type": "short_answer", "subjective": true, "prompt": "Situation: You are requesting an extension from your teacher. \"Can you give me more time? I wasn''t able to finish it.\"", "points": 1, "sampleAnswer": "Inappropriate. Revised: \"Ma''am/Sir, may I kindly request an extension for the submission? I was unable to complete the task on time.\""}, {"id": "q4", "type": "short_answer", "subjective": true, "prompt": "Situation: You are talking to your close friend about an upcoming examination. \"I would like to inform you that I am concerned about the difficulty of the examination.\"", "points": 1, "sampleAnswer": "Inappropriate (too formal). Revised: \"I''m kind of worried. The exam might be really difficult.\""}, {"id": "q5", "type": "short_answer", "subjective": true, "prompt": "Situation: You are giving feedback to a classmate about a presentation. \"Your presentation was okay, but you need to do better next time.\"", "points": 1, "sampleAnswer": "Inappropriate (too blunt). Revised: \"Your presentation was good overall. You could improve the organization of your ideas and speak a little more clearly next time.\""}]}'::jsonb FROM mod2
UNION ALL SELECT id, 6, 'activity', 'Activity 5: Using Appropriate Polite Expression', '{"instructions": "Directions: Choose the more polite response for each situation.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "A teacher corrects you. Do you say:", "points": 1, "options": ["\u201cOkay, noted.\u201d", "\u201cThank you for the correction, Ma\u2019am.\u201d"], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "You bump into someone in the hallway. Do you say:", "points": 1, "options": ["\u201cSorry, excuse me.\u201d", "\u201cWatch it.\u201d"], "correctIndex": 0}, {"id": "q3", "type": "multiple_choice", "prompt": "You\u2019re late to class. Do you say:", "points": 1, "options": ["\u201cSorry po for being late.\u201d", "\u201cI\u2019m here now, let\u2019s begin.\u201d"], "correctIndex": 0}, {"id": "q4", "type": "multiple_choice", "prompt": "You didn\u2019t understand a lecture. Do you say:", "points": 1, "options": ["\u201cWhat are you talking about?\u201d", "\u201cI didn\u2019t quite catch that. May I ask again?\u201d"], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "You\u2019re asking for an extension. Do you say:", "points": 1, "options": ["\u201cCan you move the deadline?\u201d", "\u201cMay I respectfully request for an extension?\u201d"], "correctIndex": 1}]}'::jsonb FROM mod2
UNION ALL SELECT id, 7, 'activity', 'Activity 6: Creating Context-Appropriate Dialogues', '{"instructions": "Directions: Choose one of the situations below and create a short dialogue of 5\u20136 lines. Use language appropriate to the social context and relationship between the speakers, including tone, politeness, formality, and cultural sensitivity.\n\nChoose one situation:\nA. A student and a dean during a consultation\nB. Two classmates collaborating on a project", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Write your dialogue (5\u20136 lines) for your chosen situation.", "points": 5, "sampleAnswer": "Student: Good afternoon, Dean. May I request a short consultation? Dean: Of course, please come in. Student: Thank you. I wanted to ask about my course load for next semester. Dean: Sure, let''s go over your options together. Student: I really appreciate your time and guidance, Dean. Dean: You''re welcome; feel free to reach out anytime."}]}'::jsonb FROM mod2
UNION ALL SELECT id, 8, 'activity', 'Self-Check & Reflection', '{"instructions": "Directions: Read each question carefully and choose the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Which of the following sentences shows appropriate linguistic realization in a formal setting?", "points": 1, "options": ["\u201cHey Prof, I didn\u2019t get the lesson.\u201d", "\u201cMa\u2019am, can you repeat that part again?\u201d", "\u201cExcuse me, Ma\u2019am. May I ask a clarification regarding the topic?\u201d", "\u201cWhat did you say again, Ma\u2019am?\u201d"], "correctIndex": 2}, {"id": "q2", "type": "multiple_choice", "prompt": "Choose the better expression when making an academic apology:", "points": 1, "options": ["\u201cSorry, I just woke up.\u201d", "\u201cI apologize for being late due to personal reasons.\u201d", "\u201cBetter chill, Ma\u2019am.\u201d", "\u201cI got stuck in traffic, hence, I\u2019m late.\u201d"], "correctIndex": 1}, {"id": "q3", "type": "multiple_choice", "prompt": "Which expression would be most appropriate when speaking to a dean?", "points": 1, "options": ["\u201cDean, I need help.\u201d", "\u201cHi Sir, can I ask a question?\u201d", "\u201cGood afternoon, Dean. May I request for a short consultation?\u201d", "\u201cSir, let\u2019s talk.\u201d"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "In informal situations, which of the following is acceptable?", "points": 1, "options": ["\u201cCan I respectfully ask a favor, bro?\u201d", "\u201cHey dude, let\u2019s grab lunch!\u201d", "\u201cI humbly request your presence, bestie.\u201d", "\u201cGood evening, please allow me to join you.\u201d"], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "What is linguistic realization mainly concerned with?", "points": 1, "options": ["Forming complete sentences", "Choosing the correct spelling of words", "Using language appropriate to the context", "Speaking fluently without pauses"], "correctIndex": 2}]}'::jsonb FROM mod2
UNION ALL SELECT id, 9, 'lecture', 'Reflection, Optional Task & Closing', '{"body": "Reflection Prompt: How has technology helped you improve your use of appropriate expressions in English, especially in formal or academic situations?\n\nOptional Task: Record a one-minute video or write a short journal entry reflecting on your experiences using English in school or social settings, and how this module helped you become more aware of appropriate language use.\n\nClosing Section\nCongratulations! You''ve completed the modules designed to boost your communicative competence. Continue practicing and exploring ways to use English in meaningful, real-world situations!", "readAloudEnabled": true}'::jsonb FROM mod2;
