-- ==========================================================
-- Learning Hub - Real course content seed
-- Preliminaries + Module 1: Linguistic Competence
-- Run AFTER schema.sql and seed.sql (needs faculty1@learninghub.local).
-- Adjust the email below if your teacher account differs.
-- ==========================================================

WITH prelim_module AS (
  INSERT INTO modules (title, subject, description, teacher_id, status, sequence_order)
  VALUES (
    'Preliminaries',
    'English - Communicative Competence',
    'Introduction to the course: about the author, table of contents, and foreword.',
    (SELECT id FROM profiles WHERE email = 'faculty1@learninghub.local'),
    'approved',
    0
  )
  RETURNING id
)
INSERT INTO module_content (module_id, order_index, type, title, data)
SELECT id, 0, 'lecture', 'About the Author', '{"body": "Molina G. Rizo is a licensed professional teacher and researcher with two decades of experience in education. She earned her bachelor''s degree in Secondary Education, major in English, and her Master of Arts in English from Batangas State University—The Engineering University. She is currently pursuing a Doctor of Philosophy in English, with a major in Language and Literature, at the same institution.\n\nThroughout her career, she has taught research, language, and literature courses, with expertise in qualitative and quantitative research methodologies. She has published research and presented her work at local, national, and international levels, reflecting her commitment to meaningful learning, critical thinking, and effective communication.\n\nAs the author of Enhancing Communicative Competence: A Supplementary Instructional Material for L2 College Students, she aims to help learners develop the knowledge, skills, and confidence needed to communicate effectively in academic, social, and professional contexts. The material promotes appropriate and purposeful language use while encouraging students to become competent, confident, and responsible communicators.", "readAloudEnabled": true}'::jsonb FROM prelim_module
UNION ALL SELECT id, 1, 'lecture', 'Table of Contents', '{"body": "MODULE 1: Linguistic Competence\nAreas in Focus: Lexical, Morphological, and Syntactic Competence\n  Section 1.1: Lexical Competence\n    Activity 1: Everyday Vocabulary – Match the Term\n    Activity 2: Academic Vocabulary – Match the Term\n    Activity 3: Academic Vocabulary in Action\n    Activity 4: Vocabulary Connections – Choosing the Right Synonym\n    Activity 5: Contextual Dialogue Completion\n  Section 1.2: Morphological Competence\n    Activity 1: Word Formation Drill\n    Activity 2: Error Identification and Correction\n    Activity 3: Word Family Table\n  Section 1.3: Syntactic Competence\n    Activity 1: Sentence Unscrambling\n    Activity 2: Sentence Combination Practice\n    Activity 3: Challenge Task – Informal to Formal Conversion\nSelf-Check & Reflection / Reflection Prompt / Optional Task / Closing Section\n\nMODULE 2: Sociolinguistic Competence\nArea in Focus: Linguistic Realization\n  Section 2.1: Linguistic Realization in Varying Contexts\n    Activity 1: Expression Recasting\n    Activity 2: Writing Formal and Informal Expressions\n    Activity 3: Context Matching\n    Activity 4: Contextual Expression Revision\n    Activity 5: Using Appropriate Polite Expression\n    Activity 6: Creating Context-Appropriate Dialogues\nSelf-Check & Reflection / Reflection Prompt / Optional Task / Closing Section\n\nMODULE 3: Discourse Competence\nAreas of Focus: Unity and Cohesion\n  Section 3.1: Unity in Communication\n    Activity 1: Topic Sentence Identification\n    Activity 2: Sequencing Exercise\n    Activity 3: Paragraph Unity Check – Interactive Format\n    Activity 4: Short Paragraph Writing\n  Section 3.2: Cohesion through Language Devices\n    Activity 1: Using Appropriate Cohesive Device\n    Activity 2: Sentence Linking\n    Activity 3: Paragraph Reconstruction\n    Activity 4: Cohesion Review Writing Task\nSelf-Check & Reflection / Reflection Prompt / Optional Task / Closing Section\n\nMODULE 4: Strategic Competence\nAreas in Focus: Approximation and Reconstruction\n  Section 4.1: Approximation Strategies\n    Activity 1: Describe Without Naming\n    Activity 2: Near-Equivalent Expressions\n    Activity 3: Simulated Conversation Prompt\n    Activity 4: Guess the Object\n  Section 4.2: Reconstruction Strategies\n    Activity 1: Rephrasing for Clarity\n    Activity 2: Chat Message Repair – Interactive Quiz\n    Activity 3: Fix the Message\n    Activity 4: Listening and Message Reconstruction\nSelf-Check & Reflection / Reflection Prompt / Optional Task / Closing Section", "readAloudEnabled": false}'::jsonb FROM prelim_module
UNION ALL SELECT id, 2, 'lecture', 'Foreword', '{"body": "Effective communication is an essential skill in academic life and beyond. For college students learning English as a second language, communicative competence involves more than knowing vocabulary and grammar. It requires the ability to express ideas clearly, understand others, adapt language to different contexts, organize messages effectively, and use strategies when communication becomes challenging.\n\nThis learning material, Enhancing Communicative Competence: A Supplementary Instructional Material for L2 College Students, was developed to support learners in strengthening four interconnected areas of communicative competence: linguistic, sociolinguistic, discourse, and strategic competence. The modules provide activities that develop vocabulary, word formation, sentence construction, appropriate language use, organization and connection of ideas, and communication strategies such as approximation and reconstruction.\n\nThe material also integrates technology through Microsoft Sway, providing opportunities for asynchronous learning, interactive activities, self-check exercises, reflection, and collaboration. The activities are designed around academic, social, community, and online situations, allowing learners to apply English in meaningful and practical contexts.\n\nMore than a collection of language exercises, this material seeks to develop learners who are confident, flexible, thoughtful, and responsible communicators. Through practice, reflection, and meaningful application, students are encouraged to strengthen not only their English skills but also their ability to communicate purposefully across different situations.\n\nIt is my hope that this learning material will serve as a valuable companion as learners meet the demands of academic communication and prepare for diverse social and professional contexts. May every activity help them develop not only greater competence in English, but also the confidence to use it with purpose.\n\n— The Author", "readAloudEnabled": true}'::jsonb FROM prelim_module;

