-- ==========================================================
-- Learning Hub - Real course content seed
-- Module 1: Linguistic Competence (Sections 1.1-1.3 + Self-Check)
-- Run AFTER schema.sql and seed.sql (needs faculty1@learninghub.local).
--
-- Answer keys in this file follow the official "Final References and
-- Key to Correction" document. Questions the key records as "Answers
-- may vary" carry "subjective": true — the app does not auto-score
-- them; they are held for the teacher to read and score (see
-- add_subjective_review.sql), with the key's model answer kept in
-- "sampleAnswer" for the review screen.
-- ==========================================================

WITH mod1 AS (
  INSERT INTO modules (title, subject, description, teacher_id, status, sequence_order)
  VALUES (
    'Module 1: Linguistic Competence',
    'English - Communicative Competence',
    'Areas in Focus: Lexical, Morphological, and Syntactic Competence.',
    (SELECT id FROM profiles WHERE email = 'faculty1@learninghub.local'),
    'approved',
    1
  )
  RETURNING id
)
INSERT INTO module_content (module_id, order_index, type, title, data)
SELECT id, 0, 'lecture', 'Module 1: Linguistic Competence – Overview', '{"body": "Linguistic competence refers to the knowledge and ability to use the language accurately and appropriately. It involves understanding words and their meanings, how words are formed, and how words are arranged to construct grammatically correct sentences. In this module, you will explore three related areas of linguistic competence: lexical, morphological, and syntactic competence. You will practice using appropriate vocabulary, forming words correctly, and constructing grammatically accurate sentences through activities based on academic, community, and everyday situations. These activities will help you apply your knowledge of English in meaningful communication contexts.\n\nLearning Outcomes\nAt the end of this module, you should be able to:\n1. demonstrate understanding of sociolinguistic competence and the role of context in language use;\n2. distinguish between formal and informal expressions appropriate for different social and communicative situations;\n3. use appropriate language, politeness, tone, and culturally sensitive expressions in academic, social, and everyday interactions; and\n4. create context-appropriate expressions and dialogues that demonstrate effective and socially appropriate communication.", "readAloudEnabled": true}'::jsonb FROM mod1
UNION ALL SELECT id, 1, 'lecture', 'Section 1.1: Lexical Competence', '{"body": "Lexical competence is a fundamental component of effective communication. It involves more than knowing words; learners also need to understand their meanings and use them appropriately in different situations. In this lesson, you will explore vocabulary commonly encountered by college freshmen in academic, community, and online settings. You will also learn how word nuances and collocations can help you choose more appropriate expressions, communicate ideas clearly, and improve your fluency in English.", "readAloudEnabled": true}'::jsonb FROM mod1
UNION ALL SELECT id, 2, 'activity', 'Activity 1: Everyday Vocabulary – Match the Term', '{"instructions": "Directions: For each everyday vocabulary word below, select its correct meaning from the dropdown.", "questions": [{"id": "q1", "type": "matching", "prompt": "Match each term to its meaning.", "points": 5, "pairs": [{"left": "Jeepney", "right": "Public transport commonly used in the Philippines"}, {"left": "Registrar''s Office", "right": "University office that manages student records"}, {"left": "Tuition", "right": "Payment for education"}, {"left": "Sari-sari Store", "right": "Small neighborhood store"}, {"left": "Barangay Clearance", "right": "Required document from your local government unit"}]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 3, 'activity', 'Activity 2: Academic Vocabulary – Match the Term', '{"instructions": "Directions: Interactive text: \"During my first week at the university, I reviewed the syllabus for each subject, attended my first lecture, and visited the campus library. I also asked about internship opportunities and checked the deadline for dropping courses.\"\n\nFor each academic term below, select its correct definition from the dropdown.", "questions": [{"id": "q1", "type": "matching", "prompt": "Match each academic term to its definition.", "points": 5, "pairs": [{"left": "Syllabus", "right": "A summary outline of topics and activities in a course"}, {"left": "Lecture", "right": "A formal educational talk given by a professor"}, {"left": "Deadline", "right": "The latest time by which something should be submitted"}, {"left": "Internship", "right": "Practical work experience in a field of study"}, {"left": "Campus", "right": "The grounds and buildings of a university"}]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 4, 'activity', 'Activity 3: Academic Vocabulary in Action', '{"instructions": "Directions: Write an original sentence using each word below. Make sure each sentence reflects a real-life academic or school-related situation. Example — Classroom: \"The classroom was prepared for our group presentation.\"", "questions": [{"id": "q1", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __portal__", "points": 1, "sampleAnswer": "The portal lets me view my grades and assignments."}, {"id": "q2", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __modules__", "points": 1, "sampleAnswer": "We were given multiple modules for asynchronous learning."}, {"id": "q3", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __enrollment__", "points": 1, "sampleAnswer": "I completed my enrollment online with minimal help."}, {"id": "q4", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __thesis__", "points": 1, "sampleAnswer": "My thesis proposal was approved after revision."}, {"id": "q5", "type": "short_answer", "subjective": true, "prompt": "Write a sentence using: __dean''s office__", "points": 1, "sampleAnswer": "I went to the Dean''s Office to ask about overload forms."}]}'::jsonb FROM mod1
UNION ALL SELECT id, 5, 'activity', 'Activity 4: Vocabulary Connections – Choosing the Right Synonym', '{"instructions": "Directions: Choose the most suitable synonym to replace the __underlined__ word in each sentence.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "The professor held a __webinar__ on mental health awareness.", "points": 1, "options": ["online lecture", "meeting"], "correctIndex": 0}, {"id": "q2", "type": "multiple_choice", "prompt": "I received __feedback__ on my performance.", "points": 1, "options": ["criticism", "response"], "correctIndex": 1}, {"id": "q3", "type": "multiple_choice", "prompt": "The school''s __repository__ stores all thesis submissions.", "points": 1, "options": ["archive", "drive"], "correctIndex": 0}, {"id": "q4", "type": "multiple_choice", "prompt": "My __assessment__ was based on quizzes and participation.", "points": 1, "options": ["test", "review"], "correctIndex": 0}, {"id": "q5", "type": "multiple_choice", "prompt": "I had a heavy __course load__ this semester.", "points": 1, "options": ["schedule", "number of subjects"], "correctIndex": 1}]}'::jsonb FROM mod1
UNION ALL SELECT id, 6, 'activity', 'Activity 5: Contextual Dialogue Completion', '{"instructions": "Directions: Complete the conversation using the most appropriate vocabulary from the box: Advisor, Cafeteria, Lecture, Scholarship, Classroom, Library.\n\nAna: \"Hey, have you submitted your ___ form?\"\nLance: \"Yes, I brought it to the ___ yesterday.\"\nAna: \"Same! I also stopped by the ___ to get lunch before heading to the ___ to return a book.\"\nLance: \"Cool! Let''s talk later after our ___ with the professor.\"", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Blank (1): \"...submitted your ___ form?\"", "points": 1, "acceptedAnswers": ["Scholarship"]}, {"id": "q2", "type": "short_answer", "prompt": "Blank (2): \"I brought it to the ___ yesterday.\"", "points": 1, "acceptedAnswers": ["Advisor", "Advisor''s Office"]}, {"id": "q3", "type": "short_answer", "prompt": "Blank (3): \"...stopped by the ___ to get lunch...\"", "points": 1, "acceptedAnswers": ["Cafeteria"]}, {"id": "q4", "type": "short_answer", "prompt": "Blank (4): \"...heading to the ___ to return a book.\"", "points": 1, "acceptedAnswers": ["Library"]}, {"id": "q5", "type": "short_answer", "prompt": "Blank (5): \"...after our ___ with the professor.\"", "points": 1, "acceptedAnswers": ["Lecture"]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 7, 'lecture', 'Section 1.2: Morphological Competence', '{"body": "Morphological competence is an important part of effective communication. It involves understanding how words are formed and how their meanings can change through the use of roots, prefixes, and suffixes. In this lesson, you will explore common word-formation patterns that can help you understand unfamiliar words, use the correct forms of words, and construct grammatically appropriate expressions. You will also learn how recognizing word families and common affixes can help you expand your vocabulary, improve your accuracy in English, and communicate your ideas more effectively.", "readAloudEnabled": true}'::jsonb FROM mod1
UNION ALL SELECT id, 8, 'activity', 'Activity 1: Word Formation Drill', '{"instructions": "Directions: Add the appropriate prefix or suffix to each root word. You may write just the affix (for example, __-ment__) or the complete word (__management__).", "questions": [{"id": "q1", "type": "short_answer", "prompt": "manage → ____", "points": 1, "acceptedAnswers": ["-ment", "ment", "management"]}, {"id": "q2", "type": "short_answer", "prompt": "enroll → ____", "points": 1, "acceptedAnswers": ["re-", "re", "re-enroll", "reenroll"]}, {"id": "q3", "type": "short_answer", "prompt": "prepare → ____", "points": 1, "acceptedAnswers": ["un-", "un", "unprepared"]}, {"id": "q4", "type": "short_answer", "prompt": "educate → ____", "points": 1, "acceptedAnswers": ["-tion", "tion", "education"]}, {"id": "q5", "type": "short_answer", "prompt": "organize → ____", "points": 1, "acceptedAnswers": ["-er", "er", "organizer"]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 9, 'activity', 'Activity 2: Error Identification and Correction', '{"instructions": "Directions: Identify and correct the morphological error in each sentence.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "The team was very disorganizated.", "points": 1, "acceptedAnswers": ["disorganized"]}, {"id": "q2", "type": "short_answer", "prompt": "Please submital the form before the deadline.", "points": 1, "acceptedAnswers": ["submit"]}, {"id": "q3", "type": "short_answer", "prompt": "They are unconfidence in speaking.", "points": 1, "acceptedAnswers": ["unconfident"]}, {"id": "q4", "type": "short_answer", "prompt": "We will preparize the documents by tomorrow.", "points": 1, "acceptedAnswers": ["prepare"]}, {"id": "q5", "type": "short_answer", "prompt": "I was misunderstook by the teacher.", "points": 1, "acceptedAnswers": ["misunderstood"]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 10, 'activity', 'Activity 3: Word Family Table', '{"instructions": "Directions: Complete the chart with related forms for each root word (noun, verb, and adjective form).", "questions": [{"id": "q1n", "type": "short_answer", "prompt": "Act — Noun form", "points": 1, "acceptedAnswers": ["action"]}, {"id": "q1v", "type": "short_answer", "prompt": "Act — Verb form", "points": 1, "acceptedAnswers": ["act"]}, {"id": "q1a", "type": "short_answer", "prompt": "Act — Adjective form", "points": 1, "acceptedAnswers": ["active"]}, {"id": "q2n", "type": "short_answer", "prompt": "Decide — Noun form", "points": 1, "acceptedAnswers": ["decision"]}, {"id": "q2v", "type": "short_answer", "prompt": "Decide — Verb form", "points": 1, "acceptedAnswers": ["decide"]}, {"id": "q2a", "type": "short_answer", "prompt": "Decide — Adjective form", "points": 1, "acceptedAnswers": ["decisive"]}, {"id": "q3n", "type": "short_answer", "prompt": "Organize — Noun form", "points": 1, "acceptedAnswers": ["organization"]}, {"id": "q3v", "type": "short_answer", "prompt": "Organize — Verb form", "points": 1, "acceptedAnswers": ["organize"]}, {"id": "q3a", "type": "short_answer", "prompt": "Organize — Adjective form", "points": 1, "acceptedAnswers": ["organized"]}, {"id": "q4n", "type": "short_answer", "prompt": "Succeed — Noun form", "points": 1, "acceptedAnswers": ["success"]}, {"id": "q4v", "type": "short_answer", "prompt": "Succeed — Verb form", "points": 1, "acceptedAnswers": ["succeed"]}, {"id": "q4a", "type": "short_answer", "prompt": "Succeed — Adjective form", "points": 1, "acceptedAnswers": ["successful"]}, {"id": "q5n", "type": "short_answer", "prompt": "Apply — Noun form", "points": 1, "acceptedAnswers": ["application"]}, {"id": "q5v", "type": "short_answer", "prompt": "Apply — Verb form", "points": 1, "acceptedAnswers": ["apply"]}, {"id": "q5a", "type": "short_answer", "prompt": "Apply — Adjective form", "points": 1, "acceptedAnswers": ["applicable"]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 11, 'lecture', 'Section 1.3: Syntactic Competence', '{"body": "Syntactic competence refers to the ability to understand and construct sentences by applying the rules governing the arrangement and relationship of words, phrases, and clauses. It enables learners to form grammatically well-structured sentences and express ideas clearly and accurately. In this lesson, you will develop your syntactic competence by practicing sentence construction, identifying correct sentence structures, and using appropriate linking words to connect ideas. These activities will help you construct clear and grammatically accurate sentences for academic and everyday communication.", "readAloudEnabled": true}'::jsonb FROM mod1
UNION ALL SELECT id, 12, 'activity', 'Activity 1: Sentence Unscrambling', '{"instructions": "Directions: Rearrange the words to form grammatically correct sentences.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Unscramble: submitted / the / already / group / has / report / our", "points": 1, "acceptedAnswers": ["Our group has already submitted the report."]}, {"id": "q2", "type": "short_answer", "prompt": "Unscramble: class / was / the / by / joined / late / student / a", "points": 1, "acceptedAnswers": ["A student joined the class late.", "The class was joined by a late student."]}, {"id": "q3", "type": "short_answer", "prompt": "Unscramble: assignments / checking / is / now / professor / the / our", "points": 1, "acceptedAnswers": ["Our professor is checking the assignments now.", "Our professor is now checking assignments."]}, {"id": "q4", "type": "short_answer", "prompt": "Unscramble: day / it / tiring / very / a / was", "points": 1, "acceptedAnswers": ["It was a very tiring day."]}, {"id": "q5", "type": "short_answer", "prompt": "Unscramble: quiet / library / in / the / be / should / we", "points": 1, "acceptedAnswers": ["We should be quiet in the library."]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 13, 'activity', 'Activity 2: Sentence Combination Practice', '{"instructions": "Directions: Combine the two sentences into one using an appropriate connector.", "questions": [{"id": "q1", "type": "short_answer", "prompt": "Combine: \"She was tired.\" + \"She finished the work.\"", "points": 1, "acceptedAnswers": ["Although she was tired, she finished the work.", "She was tired, but she finished the work."]}, {"id": "q2", "type": "short_answer", "prompt": "Combine: \"The class started.\" + \"He was still outside.\"", "points": 1, "acceptedAnswers": ["When the class started, he was still outside.", "The class started, but he was still outside."]}, {"id": "q3", "type": "short_answer", "prompt": "Combine: \"I studied hard.\" + \"I passed the exam.\"", "points": 1, "acceptedAnswers": ["Because I studied hard, I passed the exam.", "I studied hard, so I passed the exam."]}, {"id": "q4", "type": "short_answer", "prompt": "Combine: \"It rained.\" + \"We played indoors.\"", "points": 1, "acceptedAnswers": ["Since it rained, we played indoors.", "It rained, so we played indoors."]}, {"id": "q5", "type": "short_answer", "prompt": "Combine: \"The teacher arrived.\" + \"The students became silent.\"", "points": 1, "acceptedAnswers": ["As soon as the teacher arrived, the students became silent.", "When the teacher arrived, the students became silent."]}]}'::jsonb FROM mod1
UNION ALL SELECT id, 14, 'activity', 'Activity 3: Practicing Syntactic Competence', '{"instructions": "Directions: Choose the option that best completes or corrects each sentence.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "Subject-Verb Agreement: The group of students ___ preparing for the school presentation.", "points": 1, "options": ["are", "were", "is", "have"], "correctIndex": 2}, {"id": "q2", "type": "multiple_choice", "prompt": "Verb Tense: Yesterday, the students ___ their research project to the panel.", "points": 1, "options": ["present", "presented", "presenting", "have presented"], "correctIndex": 1}, {"id": "q3", "type": "multiple_choice", "prompt": "Sentence Structure: Which sentence is grammatically correct?", "points": 1, "options": ["The students finished their assignment they submitted it on time.", "The students finished their assignment, and they submitted it on time.", "The students finishing their assignment, they submitted on time.", "The students their assignment finished and submitted it on time."], "correctIndex": 1}, {"id": "q4", "type": "multiple_choice", "prompt": "Correct Use of Modifiers: Which sentence has the clearest, most appropriate placement of the modifier?", "points": 1, "options": ["The teacher explained carefully the difficult lesson to the students.", "The teacher carefully explained the difficult lesson to the students.", "The teacher explained the difficult carefully lesson to the students.", "Carefully the teacher explained to the students the difficult lesson."], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "Sentence Combination: \"The students studied diligently. They wanted to achieve high grades.\" Which sentence best combines the two ideas?", "points": 1, "options": ["The students studied diligently, because achieving high grades.", "The students studied diligently they wanted to achieve high grades.", "The students studied diligently because they wanted to achieve high grades.", "The students because wanted to achieve high grades studied diligently."], "correctIndex": 2}]}'::jsonb FROM mod1
UNION ALL SELECT id, 15, 'activity', 'Self-Check & Reflection', '{"instructions": "Directions: Read each question carefully and choose the best answer.", "questions": [{"id": "q1", "type": "multiple_choice", "prompt": "What is the correct formal version of this sentence: \"We had so many quizzes, super stress me.\"?", "points": 1, "options": ["We had lots of quizzes, so it was fun.", "We had many quizzes, and I was very stressed.", "There were lots of quizzes, and everyone passed.", "I did well despite the many quizzes."], "correctIndex": 1}, {"id": "q2", "type": "multiple_choice", "prompt": "Which word correctly completes this sentence: \"Our group has already ___ the report.\"", "points": 1, "options": ["submit", "submitting", "submitted", "submission"], "correctIndex": 2}, {"id": "q3", "type": "multiple_choice", "prompt": "Which of the following is a correct example of morphological competence?", "points": 1, "options": ["Misusing punctuation in a sentence", "Saying \"He goed to school\"", "Using \"re-enroll\" to mean enroll again", "Forgetting to capitalize a proper noun"], "correctIndex": 2}, {"id": "q4", "type": "multiple_choice", "prompt": "Which sentence uses proper academic syntax?", "points": 1, "options": ["I text u later if I get news.", "I will send you a message if I receive an update.", "Will send you update later.", "Maybe I text later when have info."], "correctIndex": 1}, {"id": "q5", "type": "multiple_choice", "prompt": "What is the best definition for the word \"tuition\"?", "points": 1, "options": ["A university building", "A type of assignment", "A payment for education", "A classroom activity"], "correctIndex": 2}]}'::jsonb FROM mod1
UNION ALL SELECT id, 16, 'lecture', 'Reflection, Optional Task & Closing', '{"body": "Reflection Prompt: How has technology helped you improve your English?\n\nOptional: Submit a one-minute video or short journal entry about your learning journey.\n\nClosing Section\nCongratulations! You''ve completed the modules designed to boost your communicative competence. Continue practicing and exploring ways to use English in meaningful, real-world situations!", "readAloudEnabled": true}'::jsonb FROM mod1;

